### ISSUE TITLE
Disable INFO open telemetry log from BigQuery

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#13131]
We started receiving this INFO log 

```
{opentelemetry_tracing.py:29} INFO - This service is instrumented using OpenTelemetry. OpenTelemetry
 could not be imported; please add opentelemetry-api and opentelemetry-instrumentation
packages in order to get BigQuery Tracing data.
```

The log entry is very annoying and should be disabled by default.

**Comment by mik-laj** [comment]
@potiuk  It seems to me that this problem should also be reported to the authors of the library. It is not a good idea to write logs while the module is importing..

**Comment by UrielMaD** [comment]
Hello @potiuk I'd like to take this one

**Comment by potiuk** [comment]
> @potiuk It seems to me that this problem should also be reported to the authors of the library. It is not a good idea to write logs while the module is importing..

For  sure - will you ?

**Comment by potiuk** [comment]
> > @potiuk It seems to me that this problem should also be reported to the authors of the library. It is not a good idea to write logs while the module is importing..
> 
> For sure - will you ?

But I thnk we need to disable it regardless in the default configuration.

**Comment by mik-laj** [comment]
> For sure - will you ?

Of course. I'm already creating the ticket.

> But I thnk we need to disable it regardless in the default configuration.

Not a very critical bug in my opinion for us to have to use workarounds on our side. If the authors of the library do not want to make changes to the library, we can try a workaround.

**Comment by mik-laj** [comment]
This is fixed in `google-cloud-bigquery==2.6.2`.

**Comment by yougyoung94** [comment]
Hello:)

I am still getting the same message... how can I fix it??
(I am using `astronomerinc/ap-airflow:2.0.0-2-buster` image)
