### ISSUE TITLE
Kubernetes Executor: non-existent upstream failed

### ISSUE THREAD

**Issue by bertrand-buffat** [apache/airflow#19329]
### Apache Airflow version

2.1.3

### Operating System

Debian GNU/Linux

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon==1.4.0
apache-airflow-providers-cncf-kubernetes==2.0.2

### Deployment

Other 3rd-party Helm chart

### What happened

Some tasks are randomly set to Upstream Failed while upstream task actually succeeded 

### What you expected to happen

I expect downstream tasks to be scheduled

### How to reproduce

Failure happens randomly during peak hours of scheduling

<img width="643" alt="Screenshot 2021-10-30 at 03 25 08" src="https://user-images.githubusercontent.com/83957187/139540485-a999a119-9ef2-4d02-87a4-007fc1d2c7dd.png">

We use Kubernetes Executor

Config for scheduler:

[scheduler]
job_heartbeat_sec = 5
clean_tis_without_dagrun_interval = 15.0
scheduler_heartbeat_sec = 5
num_runs = -1
processor_poll_interval = 1
min_file_process_interval = 300
dag_dir_list_interval = 300
print_stats_interval = 30
pool_metrics_interval = 5.0
scheduler_health_check_threshold = 30
orphaned_tasks_check_interval = 300.0
child_process_log_directory = /home/airflow/logs/scheduler
scheduler_zombie_task_threshold = 300
catchup_by_default = True
max_tis_per_query = 512
use_row_level_locking = True
max_dagruns_to_create_per_loop = 500
max_dagruns_per_loop_to_schedule = 500
schedule_after_task_execution = True
parsing_processes = 8
file_parsing_sort_mode = alphabetical
use_job_schedule = True
allow_trigger_in_future = False
dependency_detector = airflow.serialization.serialized_objects.DependencyDetector
run_duration = -1
statsd_port = 8125
statsd_prefix = airflow
max_threads = 5
authenticate = False

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by sweco** [comment]
Hey there, we're observing the same issue in a big DAG having hundreds of tasks. By looking in the scheduler logs from the moment when the downstream task was marked as `upstream_failed` it seems that it happened when a pod with the upstream task could not be started.

```
Failed to start pod ...
```

Also, looking at the successful task, it indeed has two tries, from which the first one really finished at the incriminated timestamp.

![image](https://user-images.githubusercontent.com/11132999/140761583-527a3754-a51d-410a-90b0-e596ab0e8c23.png)

**Comment by sweco** [comment]
# Steps to reproduce

1. Prepare a relatively small cluster, e.g. 1 node with 8 GB of RAM.
2. Deploy Airflow using Kubernetes executor there.
3. Prepare a DAG according to the following specification
    - It tries to run 5 tasks concurrently
    - Each task specifies 2 GB of RAM in their pod requests - i.e. the sum of requested RAM is greater than the total available RAM (5 * 2 GB = 10 GB > 8 GB)
    - Each task is taking more than 300 seconds (the scheduler does not crash immediately after 300 seconds, so be sure to put some reserve, e.g. 600 seconds)

    ```python
    t1 = []
    for i in range(5):
        t = BashOperator(
            task_id=f't1_{i}',
            bash_command='sleep 600 && echo Hello World!',
            executor_config={
                'pod_override': k8s.V1Pod(
                    spec=k8s.V1PodSpec(
                        containers=[
                            k8s.V1Container(
                                name="base",
                                resources=k8s.V1ResourceRequirements(
                                    requests={
                                        'memory': '2000Mi',
                                        'cpu': '1000m'
                                    }
                                )
                            )
                        ]
                    )
                )
            }
        )
        t1.append(t)
    
    t2 = BashOperator(
        task_id='t2',
        bash_command='sleep 20 && date',
    )

    t1 >> t2
    ```

4. Run the DAG, you should see that at least one of the tasks' pods will not be able to be run and will thus be in `Pending` state.

    ![image](https://user-images.githubusercontent.com/11132999/141490482-c2f5e424-1c0c-48f6-861e-8c95c3854572.png)

5. After ~6 minutes the pods will be deleted by the scheduler, marked as `up_for_retry` and at the same time `t2` will be marked as `upstream_failed`. The scheduler reports this error log for each task:

    ```
    ERROR - Pod "internaltestt1..." has been pending for longer than 300 seconds.It will be deleted and set to failed.
    ```

    In the next screenshot we can see the upstream task, whose pod was deleted, marked as `up_for_retry` and `t2` marked as `upstream_failed` even though the upstream task can still succeed running on the second try.

    ![image](https://user-images.githubusercontent.com/11132999/141489993-752fe86b-2a3b-49ee-b14b-4066d9ea0c23.png)

**Comment by romainfage** [comment]
Hello all!

When looking at the issue and logs, We may have understood why the task is set to `upstream_failed` whereas the task is retrying. (we are using Airflow 2.1.3)

We are getting this logs inside our scheduler:

```bash
{kubernetes_executor.py:368} INFO - Attempting to finish pod; pod_id: POD_ID_1; state: failed; annotations: {'dag_id': 'DAG1', 'task_id': 'TASK_ID', 'execution_date': '2021-10-29T13:05:00+00:00', 'try_number': '1'}
{kubernetes_executor.py:546} INFO - Changing state of (TaskInstanceKey(dag_id='DAG1', task_id='TASK_ID', execution_date=datetime.datetime(2021, 10, 29, 13, 5, tzinfo=tzlocal()), try_number=1), <TaskInstanceState.FAILED: 'failed'>, 'POD_ID_1', 'airflow', '164023816') to failed
{scheduler_job.py:611} INFO - Executor reports execution of DAG1.TASK_ID execution_date=2021-10-29 13:05:00+00:00 exited with status failed for try_number 1
{scheduler_job.py:647} ERROR - Executor reports task instance <TaskInstance: DAG1.TASK_ID 2021-10-29 13:05:00+00:00 [queued]> finished (failed) although the task says its queued. (Info: None) Was the task killed externally?
{scheduler_job.py:654} INFO - Setting task instance <TaskInstance: DAG1.TASK_ID 2021-10-29 13:05:00+00:00 [queued]> state to failed as reported by executor
```

Our understanding is (as demonstrate @sweco), that K8S executors try to finished the pod that is not launched yet (maybe a timeout of any kind, I cannot currently pin point where and why the executors do that). That is why we see this log:

```bash
{kubernetes_executor.py:368} INFO - Attempting to finish pod; pod_id: POD_ID_1; state: failed; annotations: {'dag_id': 'DAG1', 'task_id': 'TASK_ID', 'execution_date': '2021-10-29T13:05:00+00:00', 'try_number': '1'}
{kubernetes_executor.py:546} INFO - Changing state of (TaskInstanceKey(dag_id='DAG1', task_id='TASK_ID', execution_date=datetime.datetime(2021, 10, 29, 13, 5, tzinfo=tzlocal()), try_number=1), <TaskInstanceState.FAILED: 'failed'>, 'POD_ID_1', 'airflow', '164023816') to failed
```

Afterward, the scheduler received an event from the scheduler that change the state of the dag to failed. We can see the reception of the event here:

```bash
{scheduler_job.py:611} INFO - Executor reports execution of DAG1.TASK_ID execution_date=2021-10-29 13:05:00+00:00 exited with status failed for try_number 1
````

Afterward, the scheduler try to handle the event, to do so it look at the current state inside the metadata db of the task. However, since the pod did not start yet, the state of the task is still `queued`. The scheduler think because the old state is `queued` and the new state is `failed`, it is not a classic behavior so someone external should have done something. That is why we see the log:

```bash
{scheduler_job.py:647} ERROR - Executor reports task instance <TaskInstance: DAG1.TASK_ID 2021-10-29 13:05:00+00:00 [queued]> finished (failed) although the task says its queued. (Info: None) Was the task killed externally?
```
We can notice the question from the scheduler `Was the task killed externally?`, meaning that it is did not sure to handle well the case.

When looking at the code, we can pinpoint [here](https://github.com/apache/airflow/blob/2.1.3/airflow/jobs/scheduler_job.py#L641-L656).  Preview:
```python
    @provide_session
    def _process_executor_events(self, session: Session = None) -> int:
            [...]
            if ti.try_number == buffer_key.try_number and ti.state == State.QUEUED:
                Stats.incr('scheduler.tasks.killed_externally')
                msg = (
                    "Executor reports task instance %s finished (%s) although the "
                    "task says its %s. (Info: %s) Was the task killed externally?"
                )
                self.log.error(msg, ti, state, ti.state, info)

                request = TaskCallbackRequest(
                    full_filepath=ti.dag_model.fileloc,
                    simple_task_instance=SimpleTaskInstance(ti),
                    msg=msg % (ti, state, ti.state, info),
                )
                self.log.info('Setting task instance %s state to %s as reported by executor', ti, state)
                ti.set_state(state)
                self.processor_agent.send_callback_to_execute(request)
```

By consequence, as the scheduler think something external marks the task as `failed` and the scheduler marks downstream tasks as `upstream_failed`. Then, afterward the task is retried, finished in success and is green in Airflow but no downstream tasks are launched since they are in state `upstream_failed`.

I don't have currently enough insight on how the Airflow scheduler code really work, so I cannot provide a proper fix to this problem, but to fix the problem, may we do:

* Provide another failure state to make difference between external task kill and airflow task kill?
* Provide more information in the event received by the scheduler from the executor on the nature of the kill?
* When the task retries, it clear the down stream task state, therefore they will not be in `upstream_failed` state?

Thank you for reading me

**Comment by eladkal** [comment]
cc @jedcunningham

**Comment by kehao95** [comment]
We are experiencing the same issue at v2.1.4. task is showing `upstream_failed`

**Comment by aprettyloner** [comment]
Hi @jedcunningham @eladkal has this bug been fixed in 2.2.1+

**Comment by aprettyloner** [comment]
> Hi @jedcunningham @eladkal has this bug been fixed in 2.2.1+?
> 
> version: 2.1.4 gitSync: enabled
> 
> We are seeing this intermittently every day with both complex and simple dags.
> 
> ### More complex dags
> ![image](https://user-images.githubusercontent.com/22802852/150417615-f74717e9-554b-4538-abe5-7214f91a2ea6.png)
> 
> ![image](https://user-images.githubusercontent.com/22802852/150417952-f5bf505e-5cc0-4738-a49d-efe02c385ca9.png)
> 
> ### Simple linear dags
> ![image](https://user-images.githubusercontent.com/22802852/150417697-e16cbe55-ce07-45c4-8b71-b477a11db5cd.png)
> 
> ![image](https://user-images.githubusercontent.com/22802852/150417831-333987c8-eb5b-4993-bf87-b46902b5754a.png)

cc @ephraimbuddy

**Comment by eladkal** [comment]
@aprettyloner does the issue still happen in latest airflow version + latest provider?

**Comment by bertrand-buffat** [comment]
In our case, we implemented a dag that monitored the problem every 10 minutes and cleared the tasks if any. Then the error ceased to appear after an upgrade from aws.
I can close the issue if you want.

**Comment by Birne94** [comment]
> In our case, we implemented a dag that monitored the problem every 10 minutes and cleared the blocked tasks if any. Then the error ceased to appear after an upgrade from aws.

@bertrand-buffat would you be able to share the code for that DAG and how you are finding/clearing the affected tasks? I think this would be very helpful for us as well.

**Comment by bertrand-buffat** [comment]
Sure.
Operator:
```
class ClearFalseUpstreamFailedTaskOperator(AirflowBandAids):
    """Clears tasks that cab appear with a state upstream failed even though there are no task failed upstream"""

    query_template = """SELECT
  upstream_failed.dag_id,
  upstream_failed.run_id,
  upstream_failed.task_id
FROM (
 SELECT dag_id, task_id, state, run_id
 FROM task_instance
 WHERE state = 'upstream_failed'
 AND start_date BETWEEN '{start_date}' and '{end_date}'
) AS upstream_failed
LEFT JOIN task_instance t
  ON t.dag_id = upstream_failed.dag_id
  AND t.run_id = upstream_failed.run_id
  AND t.state = 'failed'
WHERE t.state is null
"""

    def __init__(
        self,
        airflow_conn_id,
        hour_delta,
        *args,
        **kwargs,
    ):
        """
        Args:
            airflow_conn_id: The connection id of airflow metadata backend
            hour_delta: The delta to apply to these task instances execution date.
                        The date is used as range to look for false upstream_failed
                        task in the metadata DB.
        """
        super().__init__(*args, **kwargs)
        self.airflow_conn_id = airflow_conn_id
        self.hour_delta = hour_delta

    def execute(self, context):
        tasks_by_dags = self.get_task_per_dag_run(
            self.query_template.format(
                start_date=context["logical_date"].add(hours=-self.hour_delta),
                end_date=context["data_interval_end"],
            ),
            airflow_conn_id=self.airflow_conn_id,
        )

        if not tasks_by_dags:
            raise AirflowSkipException("No task to clear")

        for (dag_id, run_id), task_ids in tasks_by_dags.items():
            self.clear_tasks(dag_id, run_id, task_ids)
```

dag:
```
from doctolib_plugins.operators.airflow_metadata_operator import ClearFalseUpstreamFailedTaskOperator

with DAG(
    dag_id="wkf_clear_airflow_tasks",
    schedule_interval="*/10 * * * *",
    default_args=obtain_default_args(),
    max_active_runs=1,
    catchup=False,
) as dag:
    ClearFalseUpstreamFailedTaskOperator(
        task_id="clear_false_upstream_failed_tasks",
        airflow_conn_id=airflow_backend_db_conn_id,
        hour_delta=3,
    )
```
