### ISSUE TITLE
airflow db clean - Dag cleanup won't run if dag is tagged

### ISSUE THREAD

**Issue by jrggggg** [apache/airflow#23414]
### Apache Airflow version

2.3.0 (latest released)

### What happened

When running `airflow db clean`, if a to-be-cleaned dag is also tagged, a foreign key constraint in dag_tag is violated. Full error:

``` 
sqlalchemy.exc.IntegrityError: (psycopg2.errors.ForeignKeyViolation) update or delete on table "dag" violates foreign key constraint "dag_tag_dag_id_fkey" on table "dag_tag"
DETAIL:  Key (dag_id)=(some-dag-id-here) is still referenced from table "dag_tag".
```

### Operating System

Debian GNU/Linux 11 (bullseye)

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon==3.3.0
apache-airflow-providers-cncf-kubernetes==4.0.1
apache-airflow-providers-ftp==2.1.2
apache-airflow-providers-http==2.1.2
apache-airflow-providers-imap==2.2.3
apache-airflow-providers-microsoft-mssql==2.1.3
apache-airflow-providers-oracle==2.2.3
apache-airflow-providers-postgres==4.1.0
apache-airflow-providers-samba==3.0.4
apache-airflow-providers-slack==4.2.3
apache-airflow-providers-sqlite==2.1.3
apache-airflow-providers-ssh==2.4.3

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by ephraimbuddy** [comment]
Related: https://github.com/apache/airflow/issues/23206

**Comment by nirutgupta** [comment]
I am seeing the same issue in 2.3.0
`[2022-06-27, 12:27:29 UTC] {subprocess.py:92} INFO - sqlalchemy.exc.IntegrityError: (psycopg2.errors.ForeignKeyViolation) update or delete on table "dag" violates foreign key constraint "dag_tag_dag_id_fkey" on table "dag_tag"
[2022-06-27, 12:27:29 UTC] {subprocess.py:92} INFO - DETAIL:  Key (dag_id)=(test_base_config) is still referenced from table "dag_tag".`

**Comment by ephraimbuddy** [comment]
> I am seeing the same issue in 2.3.0 `[2022-06-27, 12:27:29 UTC] {subprocess.py:92} INFO - sqlalchemy.exc.IntegrityError: (psycopg2.errors.ForeignKeyViolation) update or delete on table "dag" violates foreign key constraint "dag_tag_dag_id_fkey" on table "dag_tag" [2022-06-27, 12:27:29 UTC] {subprocess.py:92} INFO - DETAIL: Key (dag_id)=(test_base_config) is still referenced from table "dag_tag".`

It's fixed in 2.3.2

**Comment by swathida-byte** [comment]
same, I still see this error
sqlalchemy.exc.IntegrityError: (psycopg2.errors.ForeignKeyViolation) update or delete on table "dag" violates foreign key constraint "dag_tag_dag_id_fkey" on table "dag_tag"
Key (dag_id)=(status_notify_QATS) is still referenced from table "dag_tag".

**Comment by anka0618** [comment]
Any suggestions would be appreciated.

**Comment by ephraimbuddy** [comment]
If you are still seeing this issue, please create a new issue and describe your setup and how to reproduce it. Thanks
