### ISSUE TITLE
Celery worker enters a catatonic state after redis restart

### ISSUE THREAD

**Issue by wolfier** [apache/airflow#26542]
### Apache Airflow version

main (development)

### What happened

Worker seems to be stuck in a catatonic state where queued tasks instance messages are not consumed from redis.

Redis did restart while the worker remained as is. The worker did output logs that indicated a loss in connection but was able to reconnect after redis came back online.

```
[2022-09-19 23:58:00,794: ERROR/MainProcess] consumer: Cannot connect to redis://:**@accurate-axis-9558-redis:6379/0: Error 111 connecting to accurate-axis-9558-redis:6379. Connection refused..
Trying again in 2.00 seconds... (1/100)

[2022-09-19 23:58:03,802: ERROR/MainProcess] consumer: Cannot connect to redis://:**@accurate-axis-9558-redis:6379/0: Error 111 connecting to accurate-axis-9558-redis:6379. Connection refused..
Trying again in 4.00 seconds... (2/100)

[2022-09-19 23:58:08,830: ERROR/MainProcess] consumer: Cannot connect to redis://:**@accurate-axis-9558-redis:6379/0: Error 111 connecting to accurate-axis-9558-redis:6379. Connection refused..
Trying again in 6.00 seconds... (3/100)

[2022-09-19 23:58:15,866: ERROR/MainProcess] consumer: Cannot connect to redis://:**@accurate-axis-9558-redis:6379/0: Error 111 connecting to accurate-axis-9558-redis:6379. Connection refused..
Trying again in 8.00 seconds... (4/100)

[2022-09-19 23:58:24,890: ERROR/MainProcess] consumer: Cannot connect to redis://:**@accurate-axis-9558-redis:6379/0: Error 111 connecting to accurate-axis-9558-redis:6379. Connection refused..
Trying again in 10.00 seconds... (5/100)

[2022-09-19 23:58:34,907: INFO/MainProcess] Connected to redis://:**@accurate-axis-9558-redis:6379/0
[2022-09-19 23:58:34,915: INFO/MainProcess] mingle: searching for neighbors
[2022-09-19 23:58:35,923: INFO/MainProcess] mingle: all alone
```

### What you think should happen instead

After redis comes back online and the worker connected again, the worker should consume the messages and execute queued task instances.

### How to reproduce

1. Delete the existing redis pod and the worker should be unable to connect to redis
2. Redis restarts and the worker connects as expected
3. Worker does not consume new messages (queued task instances)

### Operating System

N/A

### Deployment

Astronomer

### Anything else

There was a [Github Discussion](https://github.com/celery/celery/discussions/7276) earlier this year about this behaviour.

This didn't seem to be an issue on an early version of celery (`4.4.7`). 

The current installed version is `celery==5.2.7` and I use redis versioned at `6.2.6`.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by ashb** [comment]
Hmmm, this feels like a Celery issue, as all `airflow celery worker` does is run the celery app.

(I'm not saying we shouldn't look at fixing it, just surprised that celery doesn't do it for us)

**Comment by wolfier** [comment]
Yep! I linked the [Github Discussion](https://github.com/celery/celery/discussions/7276) from celery Github.

This is more just a record to keep track of this behaviour.

**Comment by wolfier** [comment]
The new liveness probe on the Celery Worker (#25561) doesn't fix the root issue but does put in safeguards to reset the worker when workers become catatonic.

**Comment by potiuk** [comment]
> I am having exactly the same issue with my Airflow 2.5.1

Are you using the official chart that has the safeguards as mentioned in  ?

> The new liveness probe on the Celery Worker (#25561) doesn't fix the root issue but does put in safeguards to reset the worker when workers become catatonic.

**Comment by Scorpion2115** [comment]
> > I am having exactly the same issue with my Airflow 2.5.1
> 
> Are you using the official chart that has the safeguards as mentioned in ?
> 
> > The new liveness probe on the Celery Worker (#25561) doesn't fix the root issue but does put in safeguards to reset the worker when workers become catatonic.

Sorry my Airflow was deployed on normal EC2 instances, not Kubernetes.
Is there any similar fix available?

**Comment by potiuk** [comment]
Yes. You need to run similar monitoring and restarting of Celery on your own. Liveness Probe runs periodicaly check if any component is responding and will restart it when it is not. This is standard feature of K8S and since you chose tto manage airflow on your own you should add similar monitoring on your own. You can take a look at the PR and take it as an inspiration when writing yours.

Generally speaking it's a good practice to do the kind of monitoring and liveness probes, and if you choose to run your own deployment, you shoud make sure you do similar check - this is standard practice with any kinds of applications. 

Our Helm chart provides all those things out-of-the-box as an inspiration for anyone who woudl like to continue using their own deployment (you can easily run `helm install --dry-run` and you will see K8S resourrces generated, if you look  for liveness provbes in varioous components you might see what CLI commands you can use.

**Comment by RNHTTR** [comment]
> Yes. You need to run similar monitoring and restarting of Celery on your own. Liveness Probe runs periodicaly check if any component is responding and will restart it when it is not. This is standard feature of K8S and since you chose tto manage airflow on your own you should add similar monitoring on your own. You can take a look at the PR and take it as an inspiration when writing yours.
> 
> Generally speaking it's a good practice to do the kind of monitoring and liveness probes, and if you choose to run your own deployment, you shoud make sure you do similar check - this is standard practice with any kinds of applications.
> 
> Our Helm chart provides all those things out-of-the-box as an inspiration for anyone who woudl like to continue using their own deployment (you can easily run `helm install --dry-run` and you will see K8S resourrces generated, if you look for liveness provbes in varioous components you might see what CLI commands you can use.

I actually don't think the livenessProbe solves the issue in all cases. It's rare, but I still see this issue cause workers to become useless when they lose connection with Redis

**Comment by potiuk** [comment]
> @dstandish dude, it's passed about 30 minutes since after applying your solution. my celery worker was throwing `connection reset by peer.` errors and freezing very frequently, but now the problem is gone. **SINCERELY APPRECIATE TO YOUR SOLUTION!!!** 😱 👍

Should we turn into some kind of best practice doc @dstandish  :D?

**Comment by dstandish** [comment]
> @dstandish dude, it's passed about 30 minutes since after applying your solution. my celery worker was throwing `connection reset by peer.` errors and freezing very frequently, but now the problem is gone. **SINCERELY APPRECIATE TO YOUR SOLUTION!!!** 😱 👍

Amazing, very glad to hear it... let us hope it continues 🤞

**Comment by kaxil** [comment]
> We were able to improve the behavior with these settings:
> 
> ```
> AIRFLOW__CELERY_BROKER_TRANSPORT_OPTIONS__SOCKET_TIMEOUT=30
> AIRFLOW__CELERY_BROKER_TRANSPORT_OPTIONS__SOCKET_CONNECT_TIMEOUT=5
> AIRFLOW__CELERY_BROKER_TRANSPORT_OPTIONS__SOCKET_KEEPALIVE=True
> AIRFLOW__CELERY_BROKER_TRANSPORT_OPTIONS__RETRY_ON_TIMEOUT=True
> ```
> 
> In our repro (which was to force kill the redis pod) the celery worker would get stuck waiting forever for a response when it tried to heartbeat itself to the failed redis pod. I believe adding the socket timeout allows the connection to close in this scenario, which ultimately allows the container to be restarted.
> 
> There's also a similar issue reported in celery that may possibly be resolved in 5.4.0 (see [comment](https://github.com/celery/celery/discussions/7276#discussioncomment-8160246)). But I have not tested it.

We could set those in the Helm Chart too ?

**Comment by potiuk** [comment]
> We could set those in the Helm Chart too ? 

Yeah. Good idea.

**Comment by eladkal** [comment]
I'd wait with the doc changes to see if celery 5.4.0 sopves this problem from the root then we can simply bump version

**Comment by potiuk** [comment]
> I'd wait with the doc changes to see if celery 5.4.0 solves this problem from the root then we can simply bump version

I think it depends if those are "Generically applicable". I think a number of our users would still not use the latest celery, celery has quite a number of dependencies on it's own and it "adds" on top of the dependencies just plain airflow has. The problem with celery is that - similarly as in case of Airflow - the workers and dependencies of Celery share the same virtualenv that the task runs in, so there might be plenty of reasons why our users would like to use older celery version (in older Airflow)  or maybe even downgrade celery version used even in future versions of Airlfow. Celery is pretty special because it generally impacts everyone running any task with any provider combinations, so I'd imagine it migh be much harder to expect people to upgrade it to 5.4.0.

So I think if we ALSO have a way how to bring older celery configuration to "reasonable defaults", it's worth considering to explain that in the documentation and even our Helm Chart, and I am even happy to to it myself @dstandish @eladkal , but I need to know if those are defaults that are "ok" to be considered as sane defaults.

**Comment by potiuk** [comment]
And just to add a bit more context to the discussion. It's a known fact that a number of our use have some troubles with stability running Celery-based deployment. I think if we know a way to make it more stable, keeping it as "secret-sauce" makes little sense. Also some people proposed other solutions to improve stability (which might or might not be related and they are way more invasive) and possibly the stability issues might be helped with better default configuration (in docs and in chart).

I am particualarly referring to that one https://github.com/apache/airflow/pull/31829 which proposes to disable the "ack late" feature to improve stability of Airflow Celery deployment, which comes from the creator of the "user community" chart. We - so far - generally ignored that one, mostly I guessm becasue we did not want to spend time on analysing all the consequences of disabling ack late. 

I personally have a feeling that it changes a lot of promises about delivery and taks handling in Celery, and shifts the problem to other set of edge cases, but maybe, by making the defaults working "better" out-of-the-box, the reason for the "ack late disabling" migh be generally gone as that might improve Celery deployment stability?

That's just a thought and more context, the "ack late" ase bothers me for quite some time, but I do not have enough experience/knowledge in Celery to be able to provide more than just intuition, that maybe this one applied properly might solve problems that manifest in others trying other, worse effectively, things to improve the stability of celery.

**Comment by eladkal** [comment]
> So I think if we ALSO have a way how to bring older celery configuration to "reasonable defaults", it's worth considering to explain that in the documentation and even our Helm Chart, and I am even happy to to it myself @dstandish @eladkal , but I need to know if those are defaults that are "ok" to be considered as sane defaults.

I am OK with it.
If we don't know the values yet we can refer from the docs to this issue (or to github discussion) where we explain consideration and suggest a few options while letting the community to comment and participate in the discussion.

**Comment by alex-trm** [comment]
The discussion that @wolfier linked originally https://github.com/celery/celery/discussions/7276, has since been closed reporting that the issue is fixed in Celery >= 5.5.X.  I'm going to test this and report back.  People reported in the most recent comments of that discussion that upgrading has resolved this.  Really hoping that this is the case!

**Comment by potiuk** [comment]
Please do !

**Comment by alex-trm** [comment]
I am able to reliably reproduce the issue using the official Helm chart.  I haven't been able to do this before so I'd like to document the process here:

- Scale down Redis `statefulset` to 0 replicas
- Wait for worker to disconnect, and add about 10 seconds to that
- Scale up Redis `statefulset` to 1 replica

This seems to reliably disconnect the worker from Redis (expected, since the Redis pod is going down) and then reconnect the worker to Redis without the ability to run tasks.  Shouldn't take 2-3 cycles of the above steps to trigger the catatonic state where the worker says that it's connected, isn't killed by the liveness probe, but can't accept tasks from the queue.

---

I thought that it would be easier to just delete the Redis pod and have it restart without changing the number of replicas but that doesn't seem to do the trick.  The `kombu` link I posted above mentions GC issues and I'm wondering if keeping Redis down for ~10 seconds is long enough for a few connection retries and *maybe a GC loop* but not so long that the liveness probe kills the worker.  Regardless, these steps seem to reliably reproduce the issue.

**Comment by alex-trm** [comment]
I upgraded to `celery==5.5.0rc4` and ran my reproduction scenario 3x.  Every time the worker reconnected after Redis restarted it was able to start running tasks again.  I actually think https://github.com/celery/kombu/pull/2007 may have resolved the issue for Airflow Celery Executor using Redis as a queue!

@potiuk What other testing do you think would be required for this?  I'm going to upgrade our staging environment to this version and let it bake for a while.

**Comment by eladkal** [comment]
Noting we have https://github.com/apache/airflow/pull/43777 waiting for the 5.5.0 release

**Comment by alex-trm** [comment]
We're going to modify constraints to use rc4 for now to give it some time to test in staging / prod and I'll keep updating here with findings if we have any problems that continue after an upgrade w.r.t. this issue.

**Comment by alex-trm** [comment]
Would you rather have comments here or in PR?

**Comment by potiuk** [comment]
> Would you rather have comments here or in PR?

Whatever. But vest if you comment in Celery repo so that they finally release it if you confirm it fixes the issue :)

**Comment by alex-trm** [comment]
We were able to test and confirm that in production this resolved our catatonic worker issue.  Looking forward to seeing the full release of 5.5 so we can get this into Airflow officially.  @wolfier I think we may finally be done with the catatonic worker issue 💯

**Comment by eladkal** [comment]
This up to Celery to release it. I suggest to check with them if they can expedite release.
