### ISSUE TITLE
Airflow database migration fails in MySQL group replication mode

### ISSUE THREAD

**Issue by tirkarthi** [apache/airflow#27082]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

We are running MySQL in group replication mode and as per docs a primary key is required in a table. We noticed during our migration from Airflow 2.1.x to 2.3.4 that Airflow creates a temporary table to perform xcom related migrations by inserting the records and then renaming the table __airflow_tmp_xcom to xcom. The insert statement fails since the primary key is created after insertions. We have made a fix to move the primary key creation to be on the temporary table. Another possible solution would be to set the pragma as per docs. I have opened this issue for discussion since this might be helpful to others who might be running a similar MySQL setup and face this issue with this and possibly other migrations to 2.4.x .

https://github.com/apache/airflow/blob/4dd3c6a869497924617d6a6373dd7339b554f5d9/airflow/migrations/versions/0102_2_3_0_switch_xcom_table_to_use_run_id.py#L114-L124

https://dev.mysql.com/doc/refman/8.0/en/group-replication-requirements.html

> Primary Keys.  Every table that is to be replicated by the group must have a defined primary key, or primary key equivalent where the equivalent is a non-null unique key. Such keys are required as a unique identifier for every row within a table, enabling the system to determine which transactions conflict by identifying exactly which rows each transaction has modified. Group Replication has its own built-in set of checks for primary keys or primary key equivalents, and does not use the checks carried out by the [sql_require_primary_key](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_sql_require_primary_key) system variable. You may set sql_require_primary_key=ON for a server instance where Group Replication is running, and you may set the REQUIRE_TABLE_PRIMARY_KEY_CHECK option of the [CHANGE REPLICATION SOURCE TO](https://dev.mysql.com/doc/refman/8.0/en/change-replication-source-to.html) | [CHANGE MASTER TO](https://dev.mysql.com/doc/refman/8.0/en/change-master-to.html) statement to ON for a Group Replication channel. However, be aware that you might find some transactions that are permitted under Group Replication's built-in checks are not permitted under the checks carried out when you set sql_require_primary_key=ON or REQUIRE_TABLE_PRIMARY_KEY_CHECK=ON.

### What you think should happen instead

The migration should succeed without any issues.

### How to reproduce

Perform airflow db upgrade to 2.3.0 with MySQL in group replication mode.

### Operating System

Redhat

### Deployment

Other Docker-based deployment

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by ephraimbuddy** [comment]
Did you try upgrading to 2.4.1? The issue may have been fixed

**Comment by uranusjr** [comment]
It’s likely not fixed, at least I don’t see anything relevant. Would creating the pks before inserting be a sufficient fix? We can do that only for MySQL.

**Comment by tirkarthi** [comment]
Unfortunately, our upgrade target is 2.3.4 . The upgrade actually fails midway from 2.1.x to 2.3.4 and this migration is for moving some invalid data during 2.3.0 adding some new constraints. So the upgrade from 2.1.x will still fail for 2.4.x if I understand alembic migrations correctly since the file in main is the same as 2.3.4 release.

**Comment by uranusjr** [comment]
This can be fixed if a release fixes _the migration file itself_.

**Comment by ephraimbuddy** [comment]
> Unfortunately, our upgrade target is 2.3.4 . The upgrade actually fails midway from 2.1.x to 2.3.4 and this migration is for moving some invalid data during 2.3.0 adding some new constraints. So the upgrade from 2.1.x will still fail for 2.4.x if I understand alembic migrations correctly since the file in main is the same as 2.3.4 release.

Sometimes we fix issues on the migration files in a release

**Comment by tirkarthi** [comment]
> It’s likely not fixed, at least I don’t see anything relevant. Would creating the pks before inserting be a sufficient fix? We can do that only for MySQL.

Yes, that's the fix we did internally. I am also not sure how many users use the group replication setup in MySQL since I couldn't find any existing bug reports related to this but will be happy to add a PR.

**Comment by potiuk** [comment]
Ideally the fix should be to detect if group replication is on and follow different migration path @tirkarthi. 

We should not  - for example - disable it for "all mysql". 

I think we have to assume that it will be a LOT slower when you have huge database - and it's rather regardless from the database used (seen this happening in all of the relational databases). The root cause of the slowness is that most indexes are some kind of tree structure that have limited size and they require periodic re-organisations when the table grows. While this is usually pretty ok if done as the table grows naturally, when you insert many rows starting from 0, you will very likely hit such re-organisation multiple times during the insert process and it will get slower and slower as inserts progress.
