### ISSUE TITLE
Logging out from Web UI raises Airflow 405 error

### ISSUE THREAD

**Issue by Al2a2d2m** [apache/airflow#40470]
### Apache Airflow version

2.9.2

### What happened?

On airflow web UI,  connected as admin, when I try to logout, airflow raises invalid request exception  and the session keep going.
 capture :
![image](https://github.com/apache/airflow/assets/31657154/c3a1c7a9-d4f9-4560-82ca-054df2e34ee9)

### What you think should happen instead?

logout process needs to complete correctly

### How to reproduce

connected as admin and  try to logout

### Operating System

NAME="Red Hat Enterprise Linux" VERSION="8.9 (Ootpa)"

### Versions of Apache Airflow Providers

apache-airflow-providers-common-io==1.3.2
apache-airflow-providers-common-sql==1.14.1
apache-airflow-providers-fab==1.2.0
apache-airflow-providers-ftp==3.10.0
apache-airflow-providers-http==4.12.0
apache-airflow-providers-imap==3.6.1
apache-airflow-providers-jdbc==4.3.1
apache-airflow-providers-postgres==5.11.2
apache-airflow-providers-sftp==4.10.2
apache-airflow-providers-smtp==1.7.1
apache-airflow-providers-sqlite==3.8.1
apache-airflow-providers-ssh==3.11.2

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
This is a bug/incompatibility in the new FAB provider 1.2.0 after implementing https://github.com/apache/airflow/pull/40145 - seems that Airflow 2.9.2 (and before) is not compatible with the new POST-only requirement of FAB provider.

This is a problem only if you do not use constraints (that's what highly recommended in https://airflow.apache.org/docs/apache-airflow/stable/installation/installing-from-pypi.html ) - if you do not want to use constraints, you should downgrade/pin apache-airflow-providers-fab and it should fix your problem. That's a quick workaround for now until we fix it.

CC: @shahar1 : we need to find a good solution for back-compatibility - and I am not sure if we can - because Airlfow 2.9.2 and below will call the "/logout" method via GET and without CSRF. I think what we should do is to add a back-compatibilty code in logout - and allow "GET" method if airflow version <= 2.9.2

**Comment by Al2a2d2m** [comment]
@potiuk, I'm aware about the the use of constraints, but I have to comply with other constraints too. I followed your recommendation & downgraded fab provider using `pip install apache-airflow-providers-fab==1.1.1`
and it worked !! thank you ;)

**Comment by potiuk** [comment]
Glad it worked, but I will re-open it - this one is really a bug in FAB provider that we need to fix  :). You SHOULD be able to use 1.2.0 providers with earlier versions of Airlfow - so likely 1.2.1 version of FAB provider will have a compatibility code to handle it.

**Comment by eladkal** [comment]
> CC: @shahar1 : we need to find a good solution for back-compatibility - and I am not sure if we can do it for earlier Airflow versions - because Airlfow 2.9.2 and below will call the "/logout" method via GET and without CSRF. I think what we should do is to add a back-compatibilty code in logout - and allow "GET" method if airflow version <= 2.9.2

since fab provider has min version of Airflow 2.9.0 I think the simplest solution is to bump the min version to 2.9.2
I think that is reasonable enough

**Comment by shahar1** [comment]
> > CC: @shahar1 : we need to find a good solution for back-compatibility - and I am not sure if we can do it for earlier Airflow versions - because Airlfow 2.9.2 and below will call the "/logout" method via GET and without CSRF. I think what we should do is to add a back-compatibilty code in logout - and allow "GET" method if airflow version <= 2.9.2
> 
> since fab provider has min version of Airflow 2.9.0 I think the simplest solution is to bump the min version to 2.9.2 I think that is reasonable enough

I just thought about it while implementing the solution 😅
It is ready, though, so it's up to you how to proceed.

**Comment by eladkal** [comment]
Since you already implemented the solution and it's seems simple enough then we can just merge it :)

**Comment by potiuk** [comment]
> since fab provider has min version of Airflow 2.9.0 I think the simplest solution is to bump the min version to 2.9.2
> I think that is reasonable enough

There is a good reason why we should not limit it. The idea behind FAB provider is that each version is linked to a specific FAB version - because we partially vendored in security manager - and this allowed people to upgrade to newer version of fab (and security fixes it brings) without bringing Airlfow version up. So yeah - in this case it's just 2.9.1 and 2.9.2 that are affected, so once we release 2.9.3 everyone should upgrade anyway, but in general cases I think it's good to keep min Airflow version as low as we can, to allow everyone to upgrade FAB independently. 

So I treat that also as a "learning" exercice on how we can do it - this way in the future we might remember to look at those compatibilities and fix them in similar way.

**Comment by seub** [comment]
@potiuk Am I understanding your previous message correctly in that it should be fixed in 2.9.3? We are still seeing the error in 2.9.3.

**Comment by potiuk** [comment]
> @potiuk Am I understanding your previous message correctly in that it should be fixed in 2.9.3? We are still seeing the error in 2.9.3.
> 
> EDIT: I see now from the linked [PR](https://github.com/apache/airflow/pull/40479) that it sounds like the bug will be fixed in 2.10.0

Sort of. It will also  be fixed by the next FAB provider release. You will  be able to install the new FAB provider for 2.9.3 (and we might even adapt constraints to make sure 2.9.3 will come pre-installed with the right providers. That will be way faster than 2.10.0 and with no migration - just upgrading the provider.

**Comment by seub** [comment]
@potiuk Thank you. Strangely, we just checked that the version of the fab provider we're using is 1.2.1 (in our current deployment with airflow 2.9.3), and we still have the error, even though the bug [was supposed to be fixed](https://github.com/apache/airflow/blob/main/airflow/providers/fab/CHANGELOG.rst#121) with 1.2.1.

**Comment by potiuk** [comment]
> @potiuk Thank you. Strangely, we just checked that the version of the fab provider we're using is 1.2.1 (in our current deployment with airflow 2.9.3), and we still have the error, even though the bug [was supposed to be fixed](https://github.com/apache/airflow/blob/main/airflow/providers/fab/CHANGELOG.rst#121) with 1.2.1.

Yes it fixed it for 2.9.2 but there was wrong version check in the provider assuming that workaround will not be needed in 2.9.3 which was wrong assumption. The next version of FAB provider will fix it for all 2.9* (if we have 2.9.4) for example.

**Comment by Spaarsh** [comment]
It took me a while to triage this issue. I went through the master-branch code as well as the last released source code of airflow (2.10.4). I think I may have a way of solving this. Please correct me if I am wrong!

### Triaging
I thoroughly went through the entirety of the auth-related code (to the best of my ability). There is no wrong method being called. But since the FAB requires us to not allow any GET requests at the /logout API endpoint, the HTML can't be rendered when a user manually enters the URL in the browser point.

Before moving further though, I wanted to ensure that the /logout endpoint does work for POST requests. There is one instance of a JS code sending a POST request to the /logout endpoint via the ```no_roles_permissions.html```, where there is a logout button. In order to test this, I created a user with no roles using the command:
```
airflow users create \
    --username no_roles_user \
    --firstname No \
    --lastname Roles \
    --email no_roles_user@example.com \
    --password your_password \
    --role Public
```

When I then went to the /home page, the expected page showed up:
![image](https://github.com/user-attachments/assets/3593d7d9-3c63-4475-a674-afad514607c4)

When I clicked on the "logout" button, I was successfully able to log out, indicating no fault at the endpoint itself.

### Solution
Hence my solution is as follows:
We can create a new endpoint such as ```/logout_page``` which renders an HTML which has a logout button. The logout button has a JS event handler that sends the POST request to the /logout endpoint, resulting in successful logout using GUI.

This way, the GET request doesn't happen on our /logout endpoint itself (thus not violating any FAB requirements) while also enabling a GUI-based logout action.

If this is the correct approach, I am willing to open a PR.

**Comment by potiuk** [comment]
Yes. that sounds good.
