### ISSUE TITLE
OpenLineage provider emits warning about use of fork() on Python 3.12

### ISSUE THREAD

**Issue by kacpermuda** [apache/airflow#47160]
### Apache Airflow Provider(s)

openlineage

### Versions of Apache Airflow Providers

main

### Apache Airflow version

latest

### Operating System

null

### Deployment

Virtualenv installation

### What happened

There is a warning being emitted. Need to investigate alternatives and adjust provider code.
```
WARNING - /usr/local/lib/python3.12/site-packages/airflow/providers/openlineage/plugins/listener.py:400 DeprecationWarning: This process (pid=682) is multi-threaded, use of fork() may lead to deadlocks in the child.
```

### How to reproduce

Run dag with OpenLineage enabled on python 3.12

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Yeah https://discuss.python.org/t/concerns-regarding-deprecation-of-fork-with-alive-threads/33555/19 has more information on the problematic cases and why the warning was added.

**Comment by kacpermuda** [comment]
This still needs fixing, but with no clear ETA or bandwidth on my side.

**Comment by I-am-Uchenna** [comment]
I looked into this and the warning comes from two places in `listener.py`:

1. `_fork_execute` calling `os.fork()` directly for task instance events
2. `ProcessPoolExecutor` in the `executor` property defaulting to `fork` start method on Linux

For the `ProcessPoolExecutor`, switching to `forkserver` context is straightforward since all callables and arguments passed through `submit_callable` are already picklable.

For `_fork_execute`, the fork is intentional because the child runs user-provided extractors that may not be picklable (ruling out spawn/forkserver). The code already takes precautions for safe forking (ORM reconfiguration, os._exit), so suppressing the specific DeprecationWarning is the right approach here.

Opening a PR with the fix now.

**Comment by eladkal** [comment]
Fixed in https://github.com/apache/airflow/pull/68708

**Comment by kacpermuda** [comment]
Just a clarification, the new mode is off by default, so by default the OL will still emit the warning. We might turn it on by default in the future, but for now you might still see the warning.
