### ISSUE TITLE
Not able to authenticate FastAPI while requesting endpoints from the docs page 

### ISSUE THREAD

**Issue by atul-astronomer** [apache/airflow#47582]
### Apache Airflow version

3.0.0b2

### What happened?

Not able to authenticate FastAPI docs page (http://localhost:28080/docs)

![Image](https://github.com/user-attachments/assets/22ba5207-e486-431a-b2c4-423272211a9a)

### What you think should happen instead?

User should be able to authenticate and execute API's

### How to reproduce

Open RestAPI docs page from AF3 UI and try to authorise by giving creds admin/admin

### Operating System

Linux

### Deployment

Other

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bugraoz93** [comment]
I will check this out

**Comment by bugraoz93** [comment]
![Image](https://github.com/user-attachments/assets/09621b67-3bfb-4580-83f8-8916ab86d897)

![Image](https://github.com/user-attachments/assets/908729b4-2342-44ae-8276-31ff6c741899)

Seems like it is fixed in the `main` branch so the next release shouldn't have this issue. I have tested both signed-in and signed-out cases. Both work without providing a token or credentials.

**Comment by bugraoz93** [comment]
Closing the issue, please feel free to create another issue or tag me if it arises again.

**Comment by rawwar** [comment]
> Closing the issue, please feel free to create another issue or tag me if it arises again.

@bugraoz93 , i think the issue is for making rest api calls via swagger. That still doesn't work

**Comment by bugraoz93** [comment]
> > Closing the issue, please feel free to create another issue or tag me if it arises again.
> 
> @bugraoz93 , i think the issue is for making rest api calls via swagger. That still doesn't work

Thanks @rawwar , let me check again

**Comment by bugraoz93** [comment]
>Note
It doesn't matter what you type in the form, it won't work yet. But we'll get there.

>This is of course not the frontend for the final users, but it's a great automatic tool to document interactively all your API.
It can be used by the frontend team (that can also be yourself).
It can be used by third party applications and systems.
And it can also be used by yourself, to debug, check and test the same application.

@rawwar See here https://fastapi.tiangolo.com/tutorial/security/first-steps/#check-it 

Even if we see the button and assume it will work, it won't due to FastAPI still hasn't been implemented yet. It seems it should be used just for documentation purposes now. I think I may have found a solution to it though. Trying now. I will share more details soon.

**Comment by ashb** [comment]
I've worked out a fix in doing similar things for the Execution API. It looks like this:

<img width="780" alt="Image" src="https://github.com/user-attachments/assets/2568a7e4-1812-42b8-a018-c3b1618111ad" />

I'll do this for the core and public apis soon.

**Comment by bugraoz93** [comment]
> I've worked out a fix in doing similar things for the Execution API. It looks like this:
> 
> <img width="780" alt="Image" src="https://github.com/user-attachments/assets/2568a7e4-1812-42b8-a018-c3b1618111ad" />
> 
> I'll do this for the core and public apis soon.

Amazing! This is similar to what I found. Changing the security scheme to accept the token only. I haven't spent proper time making the changes and testing out yet. Sorry about that! I am planning to spend time on it after work.  Please let me know how can I help you. Thanks!

**Comment by vatsrahul1001** [comment]
Closing duplicate of https://github.com/apache/airflow/issues/49453

**Comment by bugraoz93** [comment]
I am sorry, I couldn't check this out! :(
