### ISSUE TITLE
Versioned dag run uses the latest version of serialized dag in the Scheduler instead of sticking to their version

### ISSUE THREAD

**Issue by vatsrahul1001** [apache/airflow#49007]
### Apache Airflow version

3.0.0

### What happened?

Previously, when a DAG had multiple versions due to changes (e.g., a task removed), running DAG runs would sometimes incorrectly use the latest serialized DAG, even if they were started with an older version. This caused tasks that should still run to be incorrectly marked as removed.

The issue was caused by the scheduler not considering bundle_version when retrieving the DAG from the dagbag, defaulting to the latest available version.

### How to reproduce

Using the dag below in a git bundle, create a run, then comment out the first section, uncomment the second quickly while the first is still in the sleep task. Run the task and you will see the astronomer task marked removed.

```
from airflow import DAG
from airflow.providers.standard.operators.bash import BashOperator

with DAG(dag_id="demo"):
    # First run
    sleep = BashOperator(task_id="sleep", bash_command="sleep 300")
    hello = BashOperator(task_id="hello", bash_command="echo 'Hello'")
    astronomer = BashOperator(task_id="astronomer", bash_command="echo 'Astonomer'")

    sleep >> hello >> astronomer

    # Second run
    #sleep = BashOperator(task_id="sleep", bash_comma
```

![Image](https://github.com/user-attachments/assets/8cf4810b-e184-4124-a3b5-3c1413f43484)

### Operating System

Linux

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by phanikumv** [comment]
Fixed by #49097

**Comment by ephraimbuddy** [comment]
While checking https://github.com/apache/airflow/issues/49047, I realized that it's the same issue with this and upon checking this, I found out that it's not resolved yet.

cc @vatsrahul1001 @atul-astronomer can you also confirm.

**Comment by atuls4441** [comment]
I am able to replicate this on latest main, first dagrun should continue running on v1 but after pushing the new changes, its not able to find the removed tasks in v2 and failing.
I am reading dags using git bundle and performed the same steps mentioned in the description.
@ephraimbuddy 

![Image](https://github.com/user-attachments/assets/550b0541-d32f-4b45-a93a-4799a6faf092)

![Image](https://github.com/user-attachments/assets/1a3e6f21-d6ae-49c8-981e-2ec445d67805)

**Comment by phanikumv** [comment]
Looks similar to #49047
