### ISSUE TITLE
Example tutorial_objectstorage DAG failing

### ISSUE THREAD

**Issue by vatsrahul1001** [apache/airflow#49149]
### Apache Airflow version

3.0.0

### What happened?

Example DAG failing error

DAG CODE: https://github.com/apache/airflow/blob/main/airflow-core/src/airflow/example_dags/tutorial_objectstorage.py

`KeyError: "Only a column name can be used for the key in a dtype mappings argument. 'fmisid' not found in columns."`

<img width="1728" alt="Image" src="https://github.com/user-attachments/assets/3cffd26d-fa6a-4d69-846e-4b8f36f736d2" />

### How to reproduce

1. Run `breeze start-airflow --executor CeleryExecutor --backend postgres --load-example-dag`
2. Run `tutorial_objectstorage`

### Operating System

Linux

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by vatsrahul1001** [comment]
Looks like API(https://opendata.fmi.fi/timeseries) being used in Example DAG is returning 400. We might need to use something else.

<img width="767" alt="Image" src="https://github.com/user-attachments/assets/230d57d6-4ee2-4460-9cf3-5cef0c49ce4d" />

**Comment by vatsrahul1001** [comment]
I see the issue here its failing at `conn.execute(f"CREATE OR REPLACE TABLE airquality_urban AS SELECT * FROM read_parquet('{path}')")`  as path in below xcom have `aws_default` which does not exits in bucket

If I pass exact path `conn.execute(f"CREATE OR REPLACE TABLE airquality_urban AS SELECT * FROM read_parquet('
s3://airflow-tutorial-data/air_quality_20250412.parquet')")` it works.



 Maybe we should not add connection details to the path. Also the way XCOM is being displayed could be better


`{'_data__': {'path': 's3://aws_default@airflow-tutorial-data/air_quality_20250412.parquet', 'kwargs': {}, 'conn_id': 'aws_default'}, '__version__': 1, '__classname__': 'airflow.sdk.io.path.ObjectStoragePath'}`

![Image](https://github.com/user-attachments/assets/96969c98-eb97-4fc9-b27b-e432d683d962)

**Comment by Yonggege123** [comment]
程序员必备！🚀 **code.mayoubang.cn**  免费 AI 代码工具，助你效率翻倍，告别加班！

**Comment by vatsrahul1001** [comment]
cc: @kaxil

**Comment by vatsrahul1001** [comment]
Regarding this same behaviour is observed in 2.10.5 as well changing priority

> I see the issue here its failing at conn.execute(f"CREATE OR REPLACE TABLE airquality_urban AS SELECT * FROM read_parquet('{path}')") as path in below xcom have aws_default which does not exits in bucket`

**Comment by kaxil** [comment]
Is this still an issue?

**Comment by vatsrahul1001** [comment]
I think yes. Let me chek on this

**Comment by HuseynA28** [comment]
Hi @vatsrahul1001 , did you manage to solve the issue? I'm getting the same error. Do you know what might be causing it?

**Comment by vatsrahul1001** [comment]
Closing fixed in [50828](https://github.com/apache/airflow/pull/50828)

**Comment by simi** [comment]
The reported issue with `conn_id` being part of `ObjectStoragePath` in `__str__` form is still present @vatsrahul1001 and breaks DuckDB usage as explained at https://airflow.apache.org/docs/apache-airflow/stable/tutorial/objectstorage.html#analyzing-the-data-with-duckdb.

**Comment by simi** [comment]
left comment at https://github.com/apache/airflow/pull/39313#issuecomment-3145186252

**Comment by potiuk** [comment]
> left comment at [#39313 (comment)](https://github.com/apache/airflow/pull/39313#issuecomment-3145186252)

Actuailly @simi -> it would be better if you open a new issue for tha.

**Comment by simi** [comment]
> > left comment at [#39313 (comment)](https://github.com/apache/airflow/pull/39313#issuecomment-3145186252)
> 
> Actuailly [@simi](https://github.com/simi) -> it would be better if you open a new issue for tha.

I think I have enough info, I'll open PR to fix with reasoning.
