### ISSUE TITLE
Error docker compose setuo fails with "jwt_secret must be set"

### ISSUE THREAD

**Issue by Lee2532** [apache/airflow#49992]
### Apache Airflow version

3.0.0

### What happened?

2025-04-30 10:58:11 ERROR:    Traceback (most recent call last):
2025-04-30 10:58:11   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/routing.py", line 692, in lifespan
2025-04-30 10:58:11     async with self.lifespan_context(app) as maybe_state:
2025-04-30 10:58:11                ^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-04-30 10:58:11   File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
2025-04-30 10:58:11     return await anext(self.gen)
2025-04-30 10:58:11            ^^^^^^^^^^^^^^^^^^^^^
2025-04-30 10:58:11   File "/home/airflow/.local/lib/python3.12/site-packages/fastapi/routing.py", line 133, in merged_lifespan
2025-04-30 10:58:11     async with original_context(app) as maybe_original_state:
2025-04-30 10:58:11                ^^^^^^^^^^^^^^^^^^^^^
2025-04-30 10:58:11   File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
2025-04-30 10:58:11     return await anext(self.gen)
2025-04-30 10:58:11            ^^^^^^^^^^^^^^^^^^^^^
2025-04-30 10:58:11   File "/home/airflow/.local/lib/python3.12/site-packages/fastapi/routing.py", line 133, in merged_lifespan
2025-04-30 10:58:11     async with original_context(app) as maybe_original_state:
2025-04-30 10:58:11                ^^^^^^^^^^^^^^^^^^^^^
2025-04-30 10:58:11   File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
2025-04-30 10:58:11     return await anext(self.gen)
2025-04-30 10:58:11            ^^^^^^^^^^^^^^^^^^^^^
2025-04-30 10:58:11   File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_fastapi/app.py", line 62, in lifespan
2025-04-30 10:58:11     await stack.enter_async_context(
2025-04-30 10:58:11   File "/usr/local/lib/python3.12/contextlib.py", line 659, in enter_async_context
2025-04-30 10:58:11     result = await _enter(cm)
2025-04-30 10:58:11              ^^^^^^^^^^^^^^^^
2025-04-30 10:58:11   File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
2025-04-30 10:58:11     return await anext(self.gen)
2025-04-30 10:58:11            ^^^^^^^^^^^^^^^^^^^^^
2025-04-30 10:58:11   File "/home/airflow/.local/lib/python3.12/site-packages/fastapi/routing.py", line 133, in merged_lifespan
2025-04-30 10:58:11     async with original_context(app) as maybe_original_state:
2025-04-30 10:58:11                ^^^^^^^^^^^^^^^^^^^^^
2025-04-30 10:58:11   File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
2025-04-30 10:58:11     return await anext(self.gen)
2025-04-30 10:58:11            ^^^^^^^^^^^^^^^^^^^^^
2025-04-30 10:58:11   File "/home/airflow/.local/lib/python3.12/site-packages/svcs/fastapi.py", line 66, in __call__
2025-04-30 10:58:11     async with self.registry, cm(app, self.registry) as state:
2025-04-30 10:58:11                               ^^^^^^^^^^^^^^^^^^^^^^
2025-04-30 10:58:11   File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
2025-04-30 10:58:11     return await anext(self.gen)
2025-04-30 10:58:11            ^^^^^^^^^^^^^^^^^^^^^
2025-04-30 10:58:11   File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_fastapi/execution_api/app.py", line 93, in lifespan
2025-04-30 10:58:11     registry.register_value(JWTValidator, _jwt_validator(), ping=JWTValidator.status)
2025-04-30 10:58:11                                           ^^^^^^^^^^^^^^^^
2025-04-30 10:58:11   File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_fastapi/execution_api/app.py", line 64, in _jwt_validator
2025-04-30 10:58:11     **get_sig_validation_args(make_secret_key_if_needed=False),
2025-04-30 10:58:11       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-04-30 10:58:11   File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_fastapi/auth/tokens.py", line 578, in get_sig_validation_args
2025-04-30 10:58:11     return {"secret_key": get_signing_key("api_auth", "jwt_secret", make_secret_key_if_needed)}
2025-04-30 10:58:11                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-04-30 10:58:11   File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_fastapi/auth/tokens.py", line 535, in get_signing_key
2025-04-30 10:58:11     raise ValueError(f"The value {section}/{key} must be set!")
2025-04-30 10:58:11 ValueError: The value api_auth/jwt_secret must be set!
2025-04-30 10:58:11 

### What you think should happen instead?

It should operate normally when a simple docker compose up is performed.

### How to reproduce

> curl -LfO 'https://airflow.apache.org/docs/apache-airflow/3.0.0/docker-compose.yaml'

> docker compose up -d

### Operating System

macOS

### Deployment

Docker-Compose

### Deployment details

Docker Compose version v2.17.3

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jehan144** [comment]
how  you fix this

**Comment by Lee2532** [comment]
> how you fix this

This was resolved in https://github.com/apache/airflow/pull/49681

**Comment by urvisism** [comment]
I can confirm this issue is still present.
I tested using the docker-compose.yaml file from the official Airflow docs (https://airflow.apache.org/docs/apache-airflow/3.0.0/docker-compose.yaml) on a fresh Ubuntu 24.04.2 LTS system, without making any modifications. I encountered the same error described above.

**Comment by Lee2532** [comment]
> 이 문제가 여전히 존재하는 것을 확인할 수 있습니다. 공식 Airflow 문서( https://airflow.apache.org/docs/apache-airflow/3.0.0/docker-compose.yaml ) 의 docker-compose.yaml 파일을 사용하여 Ubuntu 24.04.2 LTS 시스템에서 아무런 수정 없이 테스트했습니다. 그런데 위에서 설명한 것과 동일한 오류가 발생했습니다.[](https://airflow.apache.org/docs/apache-airflow/3.0.0/docker-compose.yaml)

I'm still having the same problem I think it would be good to refer to the file revised in that PR temporarily.

https://github.com/apache/airflow/pull/49993
