### ISSUE TITLE
Histogram Missing or Some DAGs

### ISSUE THREAD

**Issue by natesinger** [apache/airflow#51096]
### Apache Airflow version

3.0.1

### What happened?

When I view my DAGs the histogram is missing for some DAGs. Some are fine but many are missing. It looks like the call to `/recent_dag_runs` is not returning the expected data. I have 13 dags viewable at `/dags` but I'm only getting `recent_dag_runs` for 7 of the 13 dags. It seems like when I add a new DAG its fine but for the older ones they never show the histogram, even though they have recent runs and all are successful.

![Image](https://github.com/user-attachments/assets/6d071994-f6dc-4e9e-9f4f-af8570620a77)

![Image](https://github.com/user-attachments/assets/ca473c9e-258b-4855-805c-ccb47beda124)

```
curl 'https://airflow.k.hn.oddslab.ai/ui/dags/recent_dag_runs?dag_runs_limit=14&limit=50&offset=0' \
  -H 'accept: application/json' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'authorization: Bearer <redacted>' \
  -b 'session=649c7056-a184-4eda-a531-58468873786f.OIcYAqAdk79f833gXIEKUjk01ao' \
  -H 'priority: u=1, i' \
  -H 'referer: https://<redacted>/dags' \
  -H 'sec-ch-ua: "Google Chrome";v="137", "Chromium";v="137", "Not/A)Brand";v="24"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36'
```
```
{
    "total_entries": 7,
    "dags": [
        {
            "dag_id":
```

### What you think should happen instead?

I expect to see accurate histograms on `/dags` for all the  DAGs im trying to view.

### How to reproduce

I'm not really sure, but I am on a clean install in a k3s cluster on a single node. Airflow seems to work fine other than this. I can provide database query responses or any other API call responses if thats helpful.

### Operating System

PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"

### Versions of Apache Airflow Providers

```
(env) natesinger@tank:~/Core$ cat /etc/os-release
PRETTY_NAME="Ubuntu 24.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.2 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
(env) natesinger@tank:~/Core$ k get pods -n airflow
NAME                                     READY   STATUS    RESTARTS   AGE
airflow-api-server-7b98cd796d-bmrmz      1/1     Running   0          3d
airflow-dag-processor-5d957b45cd-8ggdg   3/3     Running   0          3d
airflow-redis-0                          1/1     Running   0          3d
airflow-scheduler-5896795f5c-wdgwj       2/2     Running   0          3d
airflow-statsd-75fdf4bc64-dnfpf          1/1     Running   0          3d
airflow-triggerer-0                      3/3     Running   0          3d
airflow-worker-0                         3/3     Running   0          3d
(reverse-i-search)`': ^C
(env) natesinger@tank:~/Core$ k exec -n airflow pod/airflow-api-server-7b98cd796d-bmrmz -it -- bash
Defaulted container "api-server" out of: api-server, wait-for-airflow-migrations (init)
airflow@airflow-api-server-7b98cd796d-bmrmz:/opt/airflow$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
airflow@airflow-api-server-7b98cd796d-bmrmz:/opt/airflow$ pip freeze | grep apache-airflow-providers
apache-airflow-providers-amazon==9.7.0
apache-airflow-providers-celery==3.10.6
apache-airflow-providers-cncf-kubernetes==10.4.3
apache-airflow-providers-common-compat==1.6.1
apache-airflow-providers-common-io==1.5.4
apache-airflow-providers-common-messaging==1.0.1
apache-airflow-providers-common-sql==1.27.0
apache-airflow-providers-docker==4.3.1
apache-airflow-providers-elasticsearch==6.2.2
apache-airflow-providers-fab==2.0.2
apache-airflow-providers-ftp==3.12.3
apache-airflow-providers-git==0.0.2
apache-airflow-providers-google==15.1.0
apache-airflow-providers-grpc==3.7.3
apache-airflow-providers-hashicorp==4.1.1
apache-airflow-providers-http==5.2.2
apache-airflow-providers-microsoft-azure==12.3.1
apache-airflow-providers-mysql==6.2.2
apache-airflow-providers-odbc==4.9.2
apache-airflow-providers-openlineage==2.2.0
apache-airflow-providers-postgres==6.1.3
apache-airflow-providers-redis==4.0.2
apache-airflow-providers-sendgrid==4.0.1
apache-airflow-providers-sftp==5.2.1
apache-airflow-providers-slack==9.0.5
apache-airflow-providers-smtp==2.0.3
apache-airflow-providers-snowflake==6.3.0
apache-airflow-providers-ssh==4.0.1
apache-airflow-providers-standard==1.1.0
```

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

K3s on a single node, see the version details for more info, happy to provide anything else you need.

### Anything else?

Thanks!

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
Fixed in https://github.com/apache/airflow/pull/51115
Upgrading to Airflow 3.0.2 should solve this

**Comment by natesinger** [comment]
@eladkal I am on Airflow 3.0.3 and still experiencing this issue.

**Comment by eladkal** [comment]
> [@eladkal](https://github.com/eladkal) I am on Airflow 3.0.3 and still experiencing this issue.

Airflow 3.0.3 is not yet released. Are you referring to RC? And if so which one?

**Comment by potiuk** [comment]
> @eladkal I am on Airflow 3.0.3 and still experiencing this issue.

Also it ususally does not help when you say "I am still experiencing an issue". What helps is if you provide logs from the version you use, screenshots and reproducible case you experience.

Can we count on that @natesinger ? Are you going to help in diagnosing the issue ? that would be cool contribution to the open-source and volunteer project that you get to use for free.
