### ISSUE TITLE
Dag Import Errors

### ISSUE THREAD

**Issue by yyyyyjg** [apache/airflow#53124]
### Apache Airflow version

3.0.2

### What happened?

i meet an error after i run airflow standalone 

`
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/develop2025/Desktop/code/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/standard/example_external_task_parent_deferrable.py", line 60, in <module>
    from tests_common.test_utils.watcher import watcher
ModuleNotFoundError: No module named 'tests_common'
`

### How to reproduce

airflow version:3.0.2

after run a standalone, will see this error

### Operating System

macos m3

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jroachgolf84** [comment]
@18270704097, what does this example DAG look like? What does your project structure look like? Does this work with other versions of Airflow?

**Comment by potiuk** [comment]
Already fixed in main in https://github.com/apache/airflow/pull/52956

**Comment by zachliu** [comment]
i tried to use

```
pip install "apache-airflow-providers-standard @ git+https://github.com/apache/airflow/#subdirectory=providers/standard"
```

to get https://github.com/apache/airflow/pull/52956 into my airflow 3.0.2 but the error persisted
i guess this doesn't belong to the provider but the main code?
