### ISSUE TITLE
UI rendering issues after migrating to Airflow 3.0.3

### ISSUE THREAD

**Issue by alexandervanloock** [apache/airflow#54410]
### Apache Airflow version

3.0.4

### What happened?

before version 3 dags where not versioned, it seems now that old tasks which were allready in the DAG are not available anymore in the main ui of the dag itself and logs are also lost

<img width="389" height="109" alt="Image" src="https://github.com/user-attachments/assets/983fe827-0168-4aad-9c7f-f0a8c26153e1" />

<img width="1300" height="359" alt="Image" src="https://github.com/user-attachments/assets/a1cdf5a1-f644-4597-a9ef-5af48c04f50f" />

, it also renders the titles of the tasks weird, it is possible to find the old tasks in the task instance explorer

<img width="1644" height="602" alt="Image" src="https://github.com/user-attachments/assets/68b03e10-6eb3-4537-b756-e724b64e566b" />

### What you think should happen instead?

it seems the addition of versioning messes with the history, I dont know if it is something we just have to accept or if there is a deeper underlining issue

### How to reproduce

have a dag with a Taskgroup and have runs on an old version of airflow
upgrade airflow to v3 and check UI

### Operating System

python:3.12.0-slim-bookworm

### Versions of Apache Airflow Providers

apache-airflow-providers-microsoft-azure==12.5.0
apache-airflow-providers-databricks==6.5.0
apache-airflow-providers-standard==1.4.1

### Deployment

Other

### Deployment details

clean install of airflow on python:3.12.0-slim-bookworm
build on a M chip mac

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by warreee** [comment]
I'm having this exact same issue!

**Comment by ArneCa** [comment]
Having the same problem, what can be the issue?

**Comment by eladkal** [comment]
Does this happens for all dags? is there a reproduce example we can verify it?

**Comment by vatsrahul1001** [comment]
I followed the steps to reproduce in the issue but was not able to replicate it. @alexandervanloock, can you confirm if this is for a specific DAG?

**Comment by alexandervanloock** [comment]
Hi, no we have this on the majority of dags

<img width="416" height="458" alt="Image" src="https://github.com/user-attachments/assets/3cce2a10-e773-465e-a94f-cb117368bb01" />
<img width="431" height="354" alt="Image" src="https://github.com/user-attachments/assets/74b83ca0-477f-42e4-b056-aa9a4280cc14" />
<img width="430" height="457" alt="Image" src="https://github.com/user-attachments/assets/d25799ef-ed10-421c-9b3c-a52694fff827" />

the only difference I see is the versioning, from the moment the dags are scheduled regularly again the runs contain all the logs, the titles in the tree though keep being truncated

we are currently on airflow 3.0.3

**Comment by bbovenzi** [comment]
Since you can still find the task instances in the table view it sounds to me like it's an issue with how we calculate task group states + version in `/ti_summaries`. cc: @dstandish 
If you check the brower's Network tab, look for endpoints with the name of the dag_run_id and see if you can find the missing task instances

**Comment by alexandervanloock** [comment]
on main load of the page I see this but do not know if this is relevant

<img width="2126" height="185" alt="Image" src="https://github.com/user-attachments/assets/24ab4905-ab6e-41d6-bb41-54a594851470" />

on trying to access the missing ones I get this

<img width="1319" height="127" alt="Image" src="https://github.com/user-attachments/assets/64508681-fbf6-491c-a53f-eea493fd91ae" />
<img width="725" height="85" alt="Image" src="https://github.com/user-attachments/assets/c0fb52e7-a8c8-4c92-87e6-68b30057dc42" />

**Comment by bbovenzi** [comment]
You know what? We refactored this a bunch for 3.1.0, so if noone can reproduce on the main branch then I think we can say this is fixed for 3.1.0

**Comment by alexandervanloock** [comment]
awesome! do you guys have an idea when this approximately could be released?

**Comment by alexandervanloock** [comment]
HI we updated to airflow 3.1.0 and we still see the issues
I also tried with a clean database underneath but the issues remain, mainly the names of tasks being cutoff in the beginning

**Comment by phanikumv** [comment]
@guan404ming would you like to take a look at this issue..

**Comment by jason810496** [comment]
> mainly the names of tasks being cutoff in the beginning

Hi @alexandervanloock, so, based on all the above context, the only remaining issue you’re seeing is that the task name is being truncated, and the rest of the issues (task instance not found after clicking the link, task group not being shown properly) have already been resolved, right?

If yes, it seems the task name truncation issue has already been solved, at least in the latest patch release (`3.1.7`):

https://github.com/user-attachments/assets/c165d1cb-703f-4038-95b7-44d7eba0cdbb
