### ISSUE TITLE
Schedulers race condition when using with kubernetes executor

### ISSUE THREAD

**Issue by yengkhoo** [apache/airflow#57618]
### Apache Airflow version

Other Airflow 2/3 version (please specify below)

### If "Other Airflow 2/3 version" selected, which one?

3.0.4

### What happened?

I'm upgrading Airflow 2.11.0 to Airflow **3.0.4**.
Using helm chart v1.18.0 to deploy on EKS, and the backend DB is AWS RDS Postgres (`db.t4g.large`, `engine 15.12`). I am using a custom image but just installing extra libraries.

In Airflow 3, when Scheduler replica is set to 2, sometimes a task will get its TaskInstance created twice with different try_number (each scheduler created one) before the first one started running. Consequently, 2 worker pods are created and one of them will fail with invalid_state error below.

I also tested this with versions **3.0.6** and **3.1.1**. I've checked that the resources for apiservers, schedulers and database usage is still far from limit. 

Extracted logs from Schedulers for a task (newest log on top):
[schedulers-log.csv](https://github.com/user-attachments/files/23261576/schedulers-log.csv)

Example error log from failed pod:
>  {"timestamp":"2025-10-25T02:49:26.475102Z","level":"info","event":"Executing workload","workload":"ExecuteTask(token='aaabbbbcccc', ti=TaskInstance(id=UUID('01994b35-8445-7dd3-bcd8-ecc39e0e448b'), task_id='spam_7.task_2', dag_id='spam_tasks_multiple_groups_dag', run_id='scheduled__2025-10-25T02:30:00+00:00', try_number=1, map_index=-1, pool_slots=1, queue='default', priority_weight=6, executor_config=None, parent_context_carrier={}, context_carrier={}, queued_dttm=None), dag_rel_path=PurePosixPath(''yeng-test/spam-dags.py'), bundle_info=BundleInfo(name='airflow-pipes', version='xx'), log_path='dag_id=spam_tasks_multiple_groups_dag/run_id=manual__2025-10-31T12:08:41+00:00/task_id=spam_7.task_2/attempt=1.log', type='ExecuteTask')","logger":"__main__"}
{"timestamp":"2025-10-25T02:49:27.001212Z","level":"info","event":"Connecting to server:","server":"http://airflow-api-server:8080/execution/","logger":"__main__"}
{"timestamp":"2025-10-25T02:49:27.068125Z","level":"info","event":"Secrets backends loaded for worker","count":1,"backend_classes":["EnvironmentVariablesBackend"],"logger":"supervisor"}
{"timestamp":"2025-10-25T02:49:27.095790Z","level":"warning","event":"Server error","detail":{"detail":{"reason":"invalid_state","message":"TI was not in a state where it could be marked as running","previous_state":"success"}},"logger":"airflow.sdk.api.client"}
{"timestamp":"2025-10-25T02:49:27.140185Z","level":"info","event":"Process exited","pid":14,"exit_code":-9,"signal_sent":"SIGKILL","logger":"supervisor"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/sdk/execution_time/execute_workload.py", line 125, in <module>
    main()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/sdk/execution_time/execute_workload.py", line 121, in main
    execute_workload(workload)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/sdk/execution_time/execute_workload.py", line 66, in execute_workload
    supervise(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/sdk/execution_time/supervisor.py", line 1829, in supervise
    process = ActivitySubprocess.start(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/sdk/execution_time/supervisor.py", line 933, in start
    proc._on_child_started(ti=what, dag_rel_path=dag_rel_path, bundle_info=bundle_info)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/sdk/execution_time/supervisor.py", line 944, in _on_child_started
    ti_context = self.client.task_instances.start(ti.id, self.pid, start_date)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/sdk/api/client.py", line 152, in start
    resp = self.client.patch(f"task-instances/{id}/run", content=body.model_dump_json())
  File "/home/airflow/.local/lib/python3.10/site-packages/httpx/_client.py", line 1218, in patch
    return self.request(
  File "/home/airflow/.local/lib/python3.10/site-packages/tenacity/__init__.py", line 338, in wrapped_f
    return copy(f, *args, **kw)
  File "/home/airflow/.local/lib/python3.10/site-packages/tenacity/__init__.py", line 477, in __call__
    do = self.iter(retry_state=retry_state)
  File "/home/airflow/.local/lib/python3.10/site-packages/tenacity/__init__.py", line 378, in iter
    result = action(retry_state)
  File "/home/airflow/.local/lib/python3.10/site-packages/tenacity/__init__.py", line 400, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.10/site-packages/tenacity/__init__.py", line 480, in __call__
    result = fn(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/sdk/api/client.py", line 735, in request
    return super().request(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/httpx/_client.py", line 825, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/home/airflow/.local/lib/python3.10/site-packages/httpx/_client.py", line 914, in send
    response = self._send_handling_auth(
  File "/home/airflow/.local/lib/python3.10/site-packages/httpx/_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/home/airflow/.local/lib/python3.10/site-packages/httpx/_client.py", line 999, in _send_handling_redirects
    raise exc
  File "/home/airflow/.local/lib/python3.10/site-packages/httpx/_client.py", line 982, in _send_handling_redirects
    hook(response)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/sdk/api/client.py", line 117, in raise_on_4xx_5xx
    return get_json_error(response) or response.raise_for_status()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/sdk/api/client.py", line 113, in get_json_error
    raise err
airflow.sdk.api.client.ServerResponseError: Server returned error

### What you think should happen instead?

When Scheduler replica is more than 1, a task's retry TI should only be created after the previous TI failed.

### How to reproduce

values:

```
revisionHistoryLimit: 1
airflowVersion: 3.0.4
images:
  airflow:
    repository: my-custom-image
    tag: dev
    pullPolicy: IfNotPresent
  useDefaultImageForMigration: false
  migrationsWaitTimeout: 60
labels: ~
networkPolicies:
  enabled: false
securityContexts:
  pod:
    runAsUser: 50000
    runAsGroup: 0
    fsGroup: 50000
    fsGroupChangePolicy: "OnRootMismatch"
    runAsNonRoot: true
  containers:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
# empty directory required to set readOnlyRootFilesystem
volumes:
  - name: tmp
    emptyDir: {}
  - name: opt
    emptyDir: {}
volumeMounts:
  - name: tmp
    mountPath: /tmp
  - name: opt
    mountPath: /opt/airflow
fernetKeySecretName: airflow-fernet-secret
env:
  - name: OPENLINEAGE_DISABLED
    value: "true"
config:
  core:
    auth_manager: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
    dagbag_import_timeout: 200
    parallelism: 200
  dag_processor:
    dag_file_processor_timeout: 300
    dag_bundle_config_list: "[{\"name\":\"airflow-dags\",\"classpath\":\"airflow.providers.git.bundles.git.GitDagBundle\",\"kwargs\":{\"subdir\":\"dags\",\"tracking_ref\":\"yeng-test-v3\",\"git_conn_id\":\"airflow-dags-dagbundle\",\"refresh_interval\":900}}]"
  database:
    sql_alchemy_pool_enabled: 'False'
    sql_alchemy_max_overflow: 20
    sql_alchemy_pool_size: 10
  kubernetes_executor:
    delete_worker_pods: true
  scheduler:
    parsing_processes: 4
  logging:
    remote_logging: 'True'
    remote_base_log_folder: s3://airflow-logs-test/
    # Connection name created to connect to S3.
    remote_log_conn_id: aws_s3_logging
    encrypt_s3_logs: False
  api:
    expose_config: 'True'
    base_url: 'https://airflow-sbx.mydomain.net'
ingress:
  apiServer:
    enabled: true
    annotations: ...
    hosts:
      - name: airflow-sbx.mydomain.net
    ingressClassName: alb
    pathType: "Prefix"
apiSecretKeySecretName: airflow-apiserver-secret
jwtSecretName: airflow-api-jwt-secret
webserver:
  defaultUser:
    enabled: false
apiServer:
  replicas: 2
  resources:
    limits:
      cpu: 3
      memory: 5Gi
    requests:
      cpu: 3
      memory: 5Gi
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: "topology.kubernetes.io/zone"
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          component: apiServer
    - maxSkew: 1
      topologyKey: "kubernetes.io/hostname"
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          component: apiServer
  apiServerConfig: ~ # i am using okta
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::xxx:role/kubernetes/AirflowRole
scheduler:
  replicas: 2
  resources:
    limits:
      cpu: 1.5
      memory: 2.5Gi
    requests:
      cpu: 1.5
      memory: 2.5Gi
  livenessProbe:
    initialDelaySeconds: 90
    periodSeconds: 50
    timeoutSeconds: 50
    failureThreshold: 20
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: "topology.kubernetes.io/zone"
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          component: scheduler
    - maxSkew: 1
      topologyKey: "kubernetes.io/hostname"
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          component: scheduler
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::xxx:role/kubernetes/AirflowRole
workers:
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 1000m
      memory: 1024Mi
  logGroomerSidecar:
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 1
        memory: 1Gi
  securityContexts:
    pod:
      runAsUser: 50000
      runAsGroup: 0
      fsGroup: 50000
      fsGroupChangePolicy: "OnRootMismatch"
      runAsNonRoot: true
    container:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: false
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::xxx:role/kubernetes/AirflowRole
podTemplate: ~
dagProcessor:
  enabled: true
  replicas: 1
executor: "KubernetesExecutor"
allowPodLaunching: true
dags:
  persistence:
    enabled: false
logs:
  persistence:
    enabled: false
redis:
  enabled: false
postgresql:
  enabled: false
createUserJob:
  useHelmHooks: false
  applyCustomEnv: false
migrateDatabaseJob:
  enabled: true
  useHelmHooks: false
  applyCustomEnv: false
  jobAnnotations:
    "argocd.argoproj.io/hook": Sync
data:
  metadataSecretName: airflow-pgbouncer-secret
  enabled: true
  replicas: 1
  revisionHistoryLimit: 1
  sslmode: "disable"
  ciphers: "normal"
  auth_type: md5
  command: ["pgbouncer", "-u", "nobody", "/etc/pgbouncer-config/pgbouncer.ini"]
  configSecretName: airflow-pgbouncer-ini-custom-secret 
  extraVolumes: ...
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 1
      memory: 1Gi
```

DAG that can reproduce the issue . After triggering, tasks will get scheduled and run as usual, but after a while failed worker pods will start showing.

```
from airflow.sdk import DAG
from airflow.operators.python import PythonOperator
from airflow.utils.task_group import TaskGroup
from datetime import datetime, timedelta
import time


# Task function
def sleep_task(task_id):
    print(f"Starting {task_id} ...")
    time.sleep(30)
    print(f"Finished {task_id}.")


# Default arguments
default_args = {
    "owner": "airflow",
    "depends_on_past": False,
    "retries": 4,
}

with DAG(
    dag_id="spam_tasks_multiple_groups_dag",
    default_args=default_args,
    description="DAG with TaskGroups, each running multiple parallel tasks",
    schedule=None, 
    start_date=datetime(2025, 1, 1),
    catchup=False,
    max_active_runs=1,
    tags=["test", "parallel", "taskgroup", "load"],
) as dag:

    start = PythonOperator(
        task_id="start",
        python_callable=lambda: print("Starting DAG run"),
    )

    # Create task groups dynamically
    task_groups = []
    for g in range(1, 10):  
        with TaskGroup(group_id=f"spam_{g}") as tg:
            for i in range(1, 6): 
                PythonOperator(
                    task_id=f"task_{i}",
                    python_callable=sleep_task,
                    op_args=[f"grp{g}_task{i}"],
                )
        task_groups.append(tg)

    end = PythonOperator(
        task_id="end",
        python_callable=lambda: print("All task groups completed."),
    )

    # Define DAG structure: start → all groups (in parallel) → end
    start >> task_groups >> end

```

pip freeze | grep apache-airflow-providers

### Operating System

Debian GNU/Linux 12 (bookworm)

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon==9.15.0
apache-airflow-providers-celery==3.12.4
apache-airflow-providers-cncf-kubernetes==10.8.2
apache-airflow-providers-fab==3.0.0
apache-airflow-providers-postgres==6.3.0
apache-airflow-providers-standard==1.9.0

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by pdellarciprete** [comment]
Hello @yengkhoo , were you able to reproduce this issue also in the latest Airflow 3.1.3 ?

**Comment by phanikumv** [comment]
@ephraimbuddy As discussed, could you please investigate this issue when you get a chance..

**Comment by pdellarciprete** [comment]
Just to confirm, we are experiencing the exact same issue on Airflow 3.1.1 using the KubernetesExecutor.

We see identical logs from both the scheduler and the worker pods. On the API server side, we consistently get:
```
"PATCH /execution/task-instances/019abae1-a01d-7dce-97f8-8a567196795e/run HTTP/1.1" 409 Conflict
[warning  ] Cannot start Task Instance in invalid state [airflow.api_fastapi.execution_api.routes.task_instances] loc=task_instances.py:180 previous_state=running ti_id=019abae1-a01d-7dce-97f8-8a567196795e
```

This perfectly matches the symptoms already described in this issue.

**Comment by yengkhoo** [comment]
Hey @pdellarciprete, I haven't tested with Airflow 3.1.3. I'll update the resul if I have time to test with it.

**Comment by pdellarciprete** [comment]
@yengkhoo thanks !

**Comment by yengkhoo** [comment]
Just tested on Aiflow 3.1.3, same issue still happening..

**Comment by pdellarciprete** [comment]
@ephraimbuddy any finding on this issue?

**Comment by pdellarciprete** [comment]
Hello @ephraimbuddy,

Not sure if you’ve had time to dig into this yet, but I spent some time analyzing the code and it looks like the issue may indeed stem from concurrency during the `None → SCHEDULED` transition inside `DagRun.schedule_tis()`. In particular, this seems to allow the scheduler to incorrectly increment the `try_number`.

**Relevant code:**  
https://github.com/apache/airflow/blob/main/airflow-core/src/airflow/models/dagrun.py#L2080-L2097

```python
for id_chunk in schedulable_ti_ids_chunks:
    result = session.execute(
        update(TI)
        .where(TI.id.in_(id_chunk))
        .values(
            state=TaskInstanceState.SCHEDULED,
            scheduled_dttm=timezone.utcnow(),
            try_number=case(
                (
                    or_(TI.state.is_(None), TI.state != TaskInstanceState.UP_FOR_RESCHEDULE),
                    TI.try_number + 1,
                ),
                else_=TI.try_number,
            ),
        )
        .execution_options(synchronize_session=False)
    )
    count += getattr(result, "rowcount", 0)
```

Reproducing the race condition scenario as I see it:

1. **Scheduler A** wins the race and successfully executes the `UPDATE`, setting `state = SCHEDULED` and `try_number = 1`.
2. **Scheduler B** immediately runs the same `UPDATE` on the same row. At this point, `TI.state` is already `SCHEDULED`, but the `or_` condition still evaluates to `True` (since `SCHEDULED != UP_FOR_RESCHEDULE`). As a result, Scheduler B updates `try_number` to `2`.
3. Both schedulers then move on to `_critical_section_enqueue_task_instances()` and each believes it owns a runnable task instance (A with try 1, B with try 2).

One possible mitigation could be to explicitly exclude tasks that are already in the `SCHEDULED` state in the `WHERE` clause, for example:

```python
.where(TI.state.is_not_(TaskInstanceState.SCHEDULED))
```

Or if you prefer:

```python
.where(TI.state.in_(airflow.ti_deps.dependencies_states.SCHEDULEABLE_STATES))
```

Because I believe there is a *Read-Write Gap* since the moment the `schedulable_tis` are retrieved [here](https://github.com/apache/airflow/blob/3.1.3/airflow-core/src/airflow/jobs/scheduler_job_runner.py#L2004) and the moment they change the state to `SCHEDULED` [here](https://github.com/apache/airflow/blob/3.1.3/airflow-core/src/airflow/jobs/scheduler_job_runner.py#L2020) 

Happy to hear your thoughts — I might be overlooking something subtle here.

**Comment by ephraimbuddy** [comment]
Hi @pdellarciprete , thanks for the analysis. You are not wrong, however, I think what we should do is not to allow two schedulers try to schedule task at the same time using db locks

**Comment by ephraimbuddy** [comment]
I haven't been able to reliably reproduce this. However, I have had cases where pod status stayed unknown while the Ti is successful. I haven't found the root cause

**Comment by pdellarciprete** [comment]
Hello @ephraimbuddy, 
thanks for looking into it. We were able to reproduce it simply scheduling very frequent executions on our Airflow instance in stage. You will start notice from time to time `409 Conflict` on the API Server logs.

**Comment by ephraimbuddy** [comment]
> Hello [@ephraimbuddy](https://github.com/ephraimbuddy), thanks for looking into it. We were able to reproduce it simply scheduling very frequent executions on our Airflow instance in stage. You will start notice from time to time `409 Conflict` on the API Server logs.

Nice. Let me try that

**Comment by pdellarciprete** [comment]
One question on the proposed approach though: 
do you see any limitations or edge cases with using an optimistic locking strategy instead — by tightening the WHERE condition at write time — rather than introducing a pessimistic database lock to prevent concurrent scheduling?

I’m curious whether an optimistic approach could sufficiently mitigate the race without the overhead and contention risks of DB-level locking.

**Comment by ephraimbuddy** [comment]
> One question on the proposed approach though: do you see any limitations or edge cases with using an optimistic locking strategy instead — by tightening the WHERE condition at write time — rather than introducing a pessimistic database lock to prevent concurrent scheduling?
> 
> I’m curious whether an optimistic approach could sufficiently mitigate the race without the overhead and contention risks of DB-level locking.

Are you saying that there is no possibility of having two schedulers picking the same TIs and both scheduling at the same time or a milliseconds apart?

**Comment by pdellarciprete** [comment]
> Nice. Let me try that

The environment where we are facing the issue more is one where we have hourly executions (around 500 executions), all of them scheduled at the same minute. There we have 4 schedulers running.

**Comment by pdellarciprete** [comment]
> > One question on the proposed approach though: do you see any limitations or edge cases with using an optimistic locking strategy instead — by tightening the WHERE condition at write time — rather than introducing a pessimistic database lock to prevent concurrent scheduling?
> > I’m curious whether an optimistic approach could sufficiently mitigate the race without the overhead and contention risks of DB-level locking.
> 
> Are you saying that there is no possibility of having two schedulers picking the same TIs and both scheduling at the same time or a milliseconds apart?

I am saying that, due to the high-availability (HA) design, it is entirely possible—and expected—that two schedulers will simultaneously pick up the same Task Instance (TI) as eligible during their respective read phases.
The fix relies on forcing the subsequent write operation (the update to SCHEDULED) to become the exclusive claim check.

The updates of the scheduler B that arrive 2nd affects 0 rows, and the Python code sees `rowcount = 0` 

This result signals to Scheduler B: "This Task Instance has already been successfully claimed and advanced by a competing process." Scheduler B immediately and safely discards management of that specific TI for the current step, preventing the flawed CASE statement from running and corrupting the `try_number`.

The concurrency issue is sporadic because the race window is extremely narrow, so just when it happens the `rowcount` of the second update will be `0`.

**Comment by ephraimbuddy** [comment]
> > > One question on the proposed approach though: do you see any limitations or edge cases with using an optimistic locking strategy instead — by tightening the WHERE condition at write time — rather than introducing a pessimistic database lock to prevent concurrent scheduling?
> > > I’m curious whether an optimistic approach could sufficiently mitigate the race without the overhead and contention risks of DB-level locking.
> > 
> > 
> > Are you saying that there is no possibility of having two schedulers picking the same TIs and both scheduling at the same time or a milliseconds apart?
> 
> I am saying that, due to the high-availability (HA) design, it is entirely possible—and expected—that two schedulers will simultaneously pick up the same Task Instance (TI) as eligible during their respective read phases. The fix relies on forcing the subsequent write operation (the update to SCHEDULED) to become the exclusive claim check.
> 
> The updates of the scheduler B that arrive 2nd affects 0 rows, and the Python code sees `rowcount = 0`
> 
> This result signals to Scheduler B: "This Task Instance has already been successfully claimed and advanced by a competing process." Scheduler B immediately and safely discards management of that specific TI for the current step, preventing the flawed CASE statement from running and corrupting the `try_number`.
> 
> The concurrency issue is sporadic because the race window is extremely narrow, so just when it happens the `rowcount` of the second update will be `0`.

Since you have reproduced it, can you apply the patch to your deployment and give us feedback?

**Comment by pdellarciprete** [comment]
Hello @ephraimbuddy, 
I tested the patch #59234 and it looks good so far. I no longer see multiple schedulers picking the same task concurrently, and I haven’t noticed any regressions in other scenarios.

However, I’ve observed another unexpected behavior that seems to cause wasted task attempts.
Below is a concrete example captured from the logs, summarized in a timeline:

| Time (UTC) | Scheduler ID | Action / Source | Try / Run Status | Significance of Event |
|------------|--------------|-----------------|------------------|-----------------------|
| 04:42:29.146 | A (nzlm5) | Add task | TI: Try 1 (→ QUEUED) | Scheduler A dispatches the first attempt. |
| 04:42:29.886 | A | Received executor event with state queued | TI: Try 1 (QUEUED) | A confirms the task is in the executor queue. |
| 04:43:58.258 | B (rkv75) | Reset the following 12 orphaned TaskInstances | TI: Try 1 (→ SCHEDULED/None) | **Critical Failure 1:** Scheduler B/C incorrectly declared A's task (Try 1) as "orphaned" and reset its state, making it available for rescheduling. |
| 04:44:01.747 | B (rkv75) | 7 tasks up for execution | TI: Try 1 (SCHEDULED) | B picks up the just-reset task as a new job candidate. |
| 04:44:01.790 | B (rkv75) | Add task | TI: Try 2 (→ QUEUED) | **Critical Failure 2:** B re-schedules the task, creating a concurrent run (Try 2 is now running/queued). |
| 04:44:49.985 | Worker Pod (w5n0w48v) | Executing workload | TI: Try 2 (RUNNING) | Worker starts Try 2. |
| 04:45:19.337 | A (nzlm5) | Marking run successful | DagRun: SUCCESS | **Critical Failure 3:** The DagRun completes successfully while Try 2 is running and Try 1 is still technically running/failing in the background. |
| 04:45:59.754 | Worker Pod (k01e9t75) | Executing workload | TI: Try 1 (RUNNING) | The worker pod for the original Try 1 finally starts, minutes after the DagRun was marked successful. |
| 04:46:04.784 | A | Received executor event with state failed | TI: Try 1 (FAILED) | Scheduler A receives the failure event for the originally dispatched task, further confirming the state confusion. |

### Observed behavior

In short:

- A task attempt (Try 1) is queued and acknowledged by Scheduler A
- Another scheduler later "incorrectly" resets it as orphaned
- This leads to a second attempt (Try 2) being scheduled and executed
- The DagRun is marked successful while an attempt is still running
- The original attempt eventually runs and fails after the DagRun has already succeeded

This doesn’t reintroduce the original concurrency issue, but it does result in:

- Unnecessary retries
- Extra executor / worker usage
- Confusing final task state transitions

For completeness, here is the full log excerpt showing the sequence above:

```
scheduler A (workflow-manager-scheduler-77d8bd4d7f-nzlm5)
2025-12-15T04:42:29.146414Z [info     ] Add task TaskInstanceKey(dag_id='sadp_dag_128', task_id='task_5', run_id='scheduled__2025-12-15T03:15:00+00:00', try_number=1, map_index=-1) with command [ExecuteTask(token='eyJ***', ti=TaskInstance(id=UUID('019b2045-cf95-7196-9df7-4fce08dbe45a'), dag_version_id=UUID('019b1df2-bb41-7ada-b061-87fe50795ffe'), task_id='task_5', dag_id='sadp_dag_128', run_id='scheduled__2025-12-15T03:15:00+00:00', try_number=1, map_index=-1, pool_slots=1, queue='default', priority_weight=1, executor_config={}, parent_context_carrier={}, context_carrier={}), dag_rel_path=PosixPath('sadp_dag_generator.py'), bundle_info=BundleInfo(name='dags-folder', version=None), log_path='dag_id=sadp_dag_128/run_id=scheduled__2025-12-15T03:15:00+00:00/task_id=task_5/attempt=1.log', type='ExecuteTask')] [airflow.providers.cncf.kubernetes.executors.kubernetes_executor.KubernetesExecutor] loc=kubernetes_executor.py:266
scheduler A (workflow-manager-scheduler-77d8bd4d7f-nzlm5)
2025-12-15T04:42:29.886794Z [info     ] Received executor event with state queued for task instance TaskInstanceKey(dag_id='sadp_dag_128', task_id='task_5', run_id='scheduled__2025-12-15T03:15:00+00:00', try_number=1, map_index=-1) [airflow.jobs.scheduler_job_runner.SchedulerJobRunner] loc=scheduler_job_runner.py:818
scheduler A (workflow-manager-scheduler-77d8bd4d7f-nzlm5)
2025-12-15T04:42:29.919003Z [info     ] Setting external_executor_id for <TaskInstance: sadp_dag_128.task_5 scheduled__2025-12-15T03:15:00+00:00 [queued]> to 14061 [airflow.jobs.scheduler_job_runner.SchedulerJobRunner] loc=scheduler_job_runner.py:854
scheduler B (workflow-manager-scheduler-77d8bd4d7f-rkv75)
2025-12-15T04:43:48.198405Z [info     ] Adopting or resetting orphaned tasks for active dag runs [airflow.jobs.scheduler_job_runner.SchedulerJobRunner] loc=scheduler_job_runner.py:2276
scheduler C (workflow-manager-scheduler-77d8bd4d7f-rkv75)
2025-12-15T04:43:58.258654Z [info     ] Reset the following 12 orphaned TaskInstances:    <TaskInstance: sadp_dag_128.task_5 scheduled__2025-12-15T03:15:00+00:00 [queued]> ... (11 more tasks) [airflow.jobs.scheduler_job_runner.SchedulerJobRunner] loc=scheduler_job_runner.py:2342
scheduler B (workflow-manager-scheduler-77d8bd4d7f-rkv75)
2025-12-15T04:44:01.747212Z [info     ] 7 tasks up for execution: ... <TaskInstance: sadp_dag_128.task_5 scheduled__2025-12-15T03:15:00+00:00 [scheduled]> [airflow.jobs.scheduler_job_runner.SchedulerJobRunner] loc=scheduler_job_runner.py:444
scheduler B (workflow-manager-scheduler-77d8bd4d7f-rkv75)
2025-12-15T04:44:01.790234Z [info     ] Add task TaskInstanceKey(dag_id='sadp_dag_128', task_id='task_5', run_id='scheduled__2025-12-15T03:15:00+00:00', try_number=2, map_index=-1) with command [ExecuteTask(token='eyJ***', ti=TaskInstance(id=UUID('019b2045-cf95-7196-9df7-4fce08dbe45a'), dag_version_id=UUID('019b1df2-bb41-7ada-b061-87fe50795ffe'), task_id='task_5', dag_id='sadp_dag_128', run_id='scheduled__2025-12-15T03:15:00+00:00', try_number=2, map_index=-1, pool_slots=1, queue='default', priority_weight=1, executor_config={}, parent_context_carrier={}, context_carrier={}), dag_rel_path=PosixPath('sadp_dag_generator.py'), bundle_info=BundleInfo(name='dags-folder', version=None), log_path='dag_id=sadp_dag_128/run_id=scheduled__2025-12-15T03:15:00+00:00/task_id=task_5/attempt=2.log', type='ExecuteTask')] [airflow.providers.cncf.kubernetes.executors.kubernetes_executor.KubernetesExecutor] loc=kubernetes_executor.py:266
scheduler B (workflow-manager-scheduler-77d8bd4d7f-rkv75)
2025-12-15T04:44:02.860218Z [info     ] Received executor event with state queued for task instance TaskInstanceKey(dag_id='sadp_dag_128', task_id='task_5', run_id='scheduled__2025-12-15T03:15:00+00:00', try_number=2, map_index=-1) [airflow.jobs.scheduler_job_runner.SchedulerJobRunner] loc=scheduler_job_runner.py:818
scheduler B (workflow-manager-scheduler-77d8bd4d7f-rkv75)
2025-12-15T04:44:02.933014Z [info     ] Setting external_executor_id for <TaskInstance: sadp_dag_128.task_5 scheduled__2025-12-15T03:15:00+00:00 [queued]> to 14069 [airflow.jobs.scheduler_job_runner.SchedulerJobRunner] loc=scheduler_job_runner.py:854
scheduler B (workflow-manager-scheduler-77d8bd4d7f-rkv75)
2025-12-15T04:44:13.348541Z [info     ] Creating kubernetes pod for job is TaskInstanceKey(dag_id='sadp_dag_128', task_id='task_5', run_id='scheduled__2025-12-15T03:15:00+00:00', try_number=2, map_index=-1), with pod name sadp-dag-128-task-5-w5n0w48v, annotations: <omitted> [airflow.providers.cncf.kubernetes.executors.kubernetes_executor_utils.AirflowKubernetesScheduler] loc=kubernetes_executor_utils.py:590
worker pod (sadp-dag-128-task-5-w5n0w48v) 
{"timestamp":"2025-12-15T04:44:49.985783Z","level":"info","event":"Executing workload","workload":"ExecuteTask(token='eyJ***', ti=TaskInstance(id=UUID('019b2045-cf95-7196-9df7-4fce08dbe45a'), dag_version_id=UUID('019b1df2-bb41-7ada-b061-87fe50795ffe'), task_id='task_5', dag_id='sadp_dag_128', run_id='scheduled__2025-12-15T03:15:00+00:00', try_number=2, map_index=-1, pool_slots=1, queue='default', priority_weight=1, executor_config=None, parent_context_carrier={}, context_carrier={}), dag_rel_path=PurePosixPath('sadp_dag_generator.py'), bundle_info=BundleInfo(name='dags-folder', version=None), log_path='dag_id=sadp_dag_128/run_id=scheduled__2025-12-15T03:15:00+00:00/task_id=task_5/attempt=2.log', type='ExecuteTask')","logger":"__main__","filename":"execute_workload.py","lineno":56}.         
scheduler A (workflow-manager-scheduler-77d8bd4d7f-nzlm5)
2025-12-15T04:45:19.337468Z [info     ] Marking run <DagRun sadp_dag_128 @ 2025-12-15 03:15:00+00:00: scheduled__2025-12-15T03:15:00+00:00, state:running, queued_at: 2025-12-15 04:30:04.672690+00:00. run_type: scheduled> successful [airflow.models.dagrun.DagRun] loc=dagrun.py:1207
scheduler A (workflow-manager-scheduler-77d8bd4d7f-nzlm5)
2025-12-15T04:45:19.337899Z [info     ] DagRun Finished: dag_id=sadp_dag_128, logical_date=2025-12-15 03:15:00+00:00, run_id=scheduled__2025-12-15T03:15:00+00:00, run_start_date=2025-12-15 04:30:04.739972+00:00, run_end_date=2025-12-15 04:45:19.337690+00:00, run_duration=914.597718, state=success, run_type=scheduled, data_interval_start=2025-12-15 03:15:00+00:00, data_interval_end=2025-12-15 04:15:00+00:00, [airflow.models.dagrun.DagRun] loc=dagrun.py:1277
scheduler A (workflow-manager-scheduler-77d8bd4d7f-nzlm5)
2025-12-15T04:45:20.037421Z [info     ] Applying patches to pod with dag_id: sadp_dag_128 [root] loc=entrypoint.py:99
scheduler A (workflow-manager-scheduler-77d8bd4d7f-nzlm5)
2025-12-15T04:45:20.038291Z [info     ] Creating kubernetes pod for job is TaskInstanceKey(dag_id='sadp_dag_128', task_id='task_5', run_id='scheduled__2025-12-15T03:15:00+00:00', try_number=1, map_index=-1), with pod name sadp-dag-128-task-5-k01e9t75, annotations: <omitted> [airflow.providers.cncf.kubernetes.executors.kubernetes_executor_utils.AirflowKubernetesScheduler] loc=kubernetes_executor_utils.py:590
worker pod (sadp-dag-128-task-5-k01e9t75) 
{"timestamp":"2025-12-15T04:45:59.754063Z","level":"info","event":"Executing workload","workload":"ExecuteTask(token='eyJ***', ti=TaskInstance(id=UUID('019b2045-cf95-7196-9df7-4fce08dbe45a'), dag_version_id=UUID('019b1df2-bb41-7ada-b061-87fe50795ffe'), task_id='task_5', dag_id='sadp_dag_128', run_id='scheduled__2025-12-15T03:15:00+00:00', try_number=1, map_index=-1, pool_slots=1, queue='default', priority_weight=1, executor_config=None, parent_context_carrier={}, context_carrier={}), dag_rel_path=PurePosixPath('sadp_dag_generator.py'), bundle_info=BundleInfo(name='dags-folder', version=None), log_path='dag_id=sadp_dag_128/run_id=scheduled__2025-12-15T03:15:00+00:00/task_id=task_5/attempt=1.log', type='ExecuteTask')","logger":"__main__","filename":"execute_workload.py","lineno":56}
scheduler A (workflow-manager-scheduler-77d8bd4d7f-nzlm5)
2025-12-15T04:46:02.705511Z [warning  ] Event: sadp-dag-128-task-5-k01e9t75 Failed, task: sadp_dag_128.task_5.1, annotations: <omitted> [airflow.providers.cncf.kubernetes.executors.kubernetes_executor_utils.KubernetesJobWatcher] loc=kubernetes_executor_utils.py:304
scheduler A (workflow-manager-scheduler-77d8bd4d7f-nzlm5)
2025-12-15T04:46:04.782995Z [info     ] Changing state of KubernetesResults(key=TaskInstanceKey(dag_id='sadp_dag_128', task_id='task_5', run_id='scheduled__2025-12-15T03:15:00+00:00', try_number=1, map_index=-1), state=<TaskInstanceState.FAILED: 'failed'>, pod_name='sadp-dag-128-task-5-k01e9t75', namespace='workflow-manager-experimentation-priority', resource_version='1765773962632719016', failure_details={'pod_status': 'Failed', 'pod_reason': None, 'pod_message': None, 'container_state': 'terminated', 'container_reason': 'Error', 'container_message': None, 'exit_code': 1, 'container_type': 'main', 'container_name': 'base'}) to failed [airflow.providers.cncf.kubernetes.executors.kubernetes_executor.KubernetesExecutor] loc=kubernetes_executor.py:332
scheduler A (workflow-manager-scheduler-77d8bd4d7f-nzlm5)
2025-12-15T04:46:04.783295Z [warning  ] Task sadp_dag_128.task_5.1 failed in pod workflow-manager-experimentation-priority/sadp-dag-128-task-5-k01e9t75. Pod phase: Failed, reason: None, message: None, container_type: main, container_name: base, container_state: terminated, container_reason: Error, container_message: None, exit_code: 1 [airflow.providers.cncf.kubernetes.executors.kubernetes_executor.KubernetesExecutor] loc=kubernetes_executor.py:445
scheduler A (workflow-manager-scheduler-77d8bd4d7f-nzlm5)
2025-12-15T04:46:04.784337Z [info     ] Received executor event with state failed for task instance TaskInstanceKey(dag_id='sadp_dag_128', task_id='task_5', run_id='scheduled__2025-12-15T03:15:00+00:00', try_number=1, map_index=-1) [airflow.jobs.scheduler_job_runner.SchedulerJobRunner] loc=scheduler_job_runner.py:818
scheduler A (workflow-manager-scheduler-77d8bd4d7f-nzlm5)
2025-12-15T04:46:04.811357Z [info     ] TaskInstance Finished: dag_id=sadp_dag_128, task_id=task_5, run_id=scheduled__2025-12-15T03:15:00+00:00, map_index=-1, run_start_date=2025-12-15 04:44:50.091613+00:00, run_end_date=2025-12-15 04:45:09.418923+00:00, run_duration=19.32731, state=success, executor=KubernetesExecutor(parallelism=128), executor_state=failed, try_number=1, max_tries=3, pool=default_pool, queue=default, priority_weight=1, operator=PythonOperator, queued_dttm=2025-12-15 04:44:01.754200+00:00, scheduled_dttm=2025-12-15 04:44:01.273310+00:00,queued_by_job_id=14069, pid=14 [airflow.jobs.scheduler_job_runner.SchedulerJobRunner] loc=scheduler_job_runner.py:864
```

Let me know if this aligns with expected behavior or if you’d like me to test a specific configuration or scenario. Happy to dig further if useful.

**Comment by pdellarciprete** [comment]
Additionally, in the UI I can only see the second attempt

<img width="503" height="545" alt="Image" src="https://github.com/user-attachments/assets/ba2906a4-d0c3-4254-9c88-849e0582f063" />

**Comment by ephraimbuddy** [comment]
@pdellarciprete Thanks for the information. Are you using a versioned bundle like gitdagbundle?

**Comment by pdellarciprete** [comment]
> [@pdellarciprete](https://github.com/pdellarciprete) Thanks for the information. Are you using a versioned bundle like gitdagbundle?

Hello @ephraimbuddy , we are using the default `LocalDagBundle`. Do you think this can be related somehow to the issue?

**Comment by ephraimbuddy** [comment]
This seems to come from multiple schedulers creating TIs concurrently through DagRun.verify_integrity which doesn't have protection. Can you try this patch without your own patch?:

```diff
diff --git a/airflow-core/src/airflow/models/dagrun.py b/airflow-core/src/airflow/models/dagrun.py
index 89999bdbf2..cebaa58762 100644
--- a/airflow-core/src/airflow/models/dagrun.py
+++ b/airflow-core/src/airflow/models/dagrun.py
@@ -47,7 +47,7 @@ from sqlalchemy import (
     update,
 )
 from sqlalchemy.dialects import postgresql
-from sqlalchemy.exc import IntegrityError
+from sqlalchemy.exc import IntegrityError, OperationalError
 from sqlalchemy.ext.associationproxy import association_proxy
 from sqlalchemy.ext.hybrid import hybrid_property
 from sqlalchemy.ext.mutable import MutableDict
@@ -84,6 +84,7 @@ from airflow.utils.sqlalchemy import (
     ExtendedJSON,
     UtcDateTime,
     get_dialect_name,
+    is_lock_not_available_error,
     mapped_column,
     nulls_first,
     with_row_locks,
@@ -1701,6 +1702,34 @@ class DagRun(Base, LoggingMixin):
         """
         from airflow.settings import task_instance_mutation_hook
 
+        try:
+            locked_dag_run = session.scalar(
+                with_row_locks(
+                    select(DagRun).where(DagRun.dag_id == self.dag_id, DagRun.run_id == self.run_id),
+                    session=session,
+                    nowait=True,
+                )
+            )
+            if not locked_dag_run:
+                # DagRun doesn't exist (shouldn't happen, but handle gracefully)
+                self.log.warning(
+                    "DagRun %s-%s not found when trying to lock for verify_integrity",
+                    self.dag_id,
+                    self.run_id,
+                )
+                return
+        except OperationalError as e:
+            if is_lock_not_available_error(error=e):
+                # Another scheduler is already processing this DagRun, skip it
+                self.log.debug(
+                    "Skipping verify_integrity for DagRun %s-%s as it is locked by another scheduler",
+                    self.dag_id,
+                    self.run_id,
+                )
+                return
+            # Re-raise other OperationalErrors
+            raise
+
         # Set for the empty default in airflow.settings -- if it's not set this means it has been changed
         # Note: Literal[True, False] instead of bool because otherwise it doesn't correctly find the overload.
         hook_is_noop: Literal[True, False] = getattr(task_instance_mutation_hook, "is_noop", False)
```

**Comment by pdellarciprete** [comment]
Hello @ephraimbuddy , 

I will and let you know.

**Comment by pdellarciprete** [comment]
Hello @ephraimbuddy , 

Unfortunately, with the patch you proposed the race condition between 2 schedulers is still there :

```
workflow-manager-scheduler-675c578dff-sj2cl - 2025-12-15T15:32:42.776467Z [info     ] Add task TaskInstanceKey(dag_id='sadp_dag_388', task_id='task_4', run_id='scheduled__2025-12-15T14:15:00+00:00', try_number=1, map_index=-1) with command [ExecuteTask(token='eyJ***', ti=TaskInstance(id=UUID('019b2296-3005-7a2c-b53e-41c91af5a050'), dag_version_id=UUID('019b1df3-2a94-72d0-8f3d-0f78264a606f'), task_id='task_4', dag_id='sadp_dag_388', run_id='scheduled__2025-12-15T14:15:00+00:00', try_number=1, map_index=-1, pool_slots=1, queue='default', priority_weight=2, executor_config={}, parent_context_carrier={}, context_carrier={}), dag_rel_path=PosixPath('sadp_dag_generator.py'), bundle_info=BundleInfo(name='dags-folder', version=None), log_path='dag_id=sadp_dag_388/run_id=scheduled__2025-12-15T14:15:00+00:00/task_id=task_4/attempt=1.log', type='ExecuteTask')] [airflow.providers.cncf.kubernetes.executors.kubernetes_executor.KubernetesExecutor] loc=kubernetes_executor.py:266
workflow-manager-scheduler-675c578dff-5h82r - 2025-12-15T15:32:44.627322Z [info     ] Add task TaskInstanceKey(dag_id='sadp_dag_388', task_id='task_4', run_id='scheduled__2025-12-15T14:15:00+00:00', try_number=2, map_index=-1) with command [ExecuteTask(token='eyJ***', ti=TaskInstance(id=UUID('019b2296-3005-7a2c-b53e-41c91af5a050'), dag_version_id=UUID('019b1df3-2a94-72d0-8f3d-0f78264a606f'), task_id='task_4', dag_id='sadp_dag_388', run_id='scheduled__2025-12-15T14:15:00+00:00', try_number=2, map_index=-1, pool_slots=1, queue='default', priority_weight=2, executor_config={}, parent_context_carrier={}, context_carrier={}), dag_rel_path=PosixPath('sadp_dag_generator.py'), bundle_info=BundleInfo(name='dags-folder', version=None), log_path='dag_id=sadp_dag_388/run_id=scheduled__2025-12-15T14:15:00+00:00/task_id=task_4/attempt=2.log', type='ExecuteTask')] [airflow.providers.cncf.kubernetes.executors.kubernetes_executor.KubernetesExecutor] loc=kubernetes_executor.py:266
```

**Comment by pdellarciprete** [comment]
Hello @ephraimbuddy,

Just to summarize my current understanding: it appears that one SchedulerJob (the one that adopt the task first) is eventually marked as failed because its heartbeat exceeds the `scheduler_health_check_threshold`. At that point, the task is adopted by another scheduler, which increments the `try_number` (is this the intended behavior?).

However, both schedulers/executors continue executing the same task, which ultimately leads to a conflicting task state.

**Comment by pdellarciprete** [comment]
IMO, the adoption of an orphaned task should not increment the `try_number`. 
Additionally, the KubernetesExecutor should verify before creating a new Pod whether the task instance is still assigned to the same `scheduler_job_id`.

Is there a way to disable the orphaned task adoption check and simply mark the task as failed if one scheduler abandon it (like relying on task heartbeat timeout)?

**Comment by ephraimbuddy** [comment]
> Hello [@ephraimbuddy](https://github.com/ephraimbuddy),
> 
> Just to summarize my current understanding: it appears that one SchedulerJob (the one that adopt the task first) is eventually marked as failed because its heartbeat exceeds the `scheduler_health_check_threshold`. At that point, the task is adopted by another scheduler, which increments the `try_number` (is this the intended behavior?).
> 
> However, both schedulers/executors continue executing the same task, which ultimately leads to a conflicting task state.

Did you make changes to the scheduler_health_check_threshold?

**Comment by ephraimbuddy** [comment]
I was able to reproduce this with 2 api-server replicas. Working on it...

**Comment by ephraimbuddy** [comment]
log:
```log
{"timestamp":"2025-12-17T12:41:01.323063Z","level":"warning","event":"Starting call to 'airflow.sdk.api.client.Client.request', this is the 1st time calling it.","logger":"airflow.sdk.api.client","filename":"before.py","lineno":42}
{"timestamp":"2025-12-17T12:41:02.457592Z","level":"error","event":"API server error","status_code":409,"detail":{"detail":{"reason":"invalid_state","message":"TI was not in the running state so it cannot be updated","previous_state":"success"}},"message":"Server returned error","logger":"supervisor","filename":"supervisor.py","lineno":629}
{"timestamp":"2025-12-17T12:41:02.472787Z","level":"error","event":"Top level error","logger":"task","filename":"task_runner.py","lineno":1505,"error_detail":[{"exc_type":"AirflowRuntimeError","exc_value":"API_SERVER_ERROR: {'status_code': 409, 'message': 'Server returned error', 'detail': {'detail': {'reason': 'invalid_state', 'message': 'TI was not in the running state so it cannot be updated', 'previous_state': 'success'}}}","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/opt/airflow/task-sdk/src/airflow/sdk/execution_time/task_runner.py","lineno":1498,"name":"main"},{"filename":"/opt/airflow/task-sdk/src/airflow/sdk/execution_time/task_runner.py","lineno":1057,"name":"run"},{"filename":"/opt/airflow/task-sdk/src/airflow/sdk/execution_time/comms.py","lineno":207,"name":"send"},{"filename":"/opt/airflow/task-sdk/src/airflow/sdk/execution_time/comms.py","lineno":271,"name":"_get_response"},{"filename":"/opt/airflow/task-sdk/src/airflow/sdk/execution_time/comms.py","lineno":258,"name":"_from_frame"}],"is_group":false,"exceptions":[]}]}
Traceback (most recent call last):
  File "/usr/python/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/python/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/airflow/task-sdk/src/airflow/sdk/execution_time/execute_workload.py", line 126, in <module>
    main()
  File "/opt/airflow/task-sdk/src/airflow/sdk/execution_time/execute_workload.py", line 122, in main
    execute_workload(workload)
  File "/opt/airflow/task-sdk/src/airflow/sdk/execution_time/execute_workload.py", line 66, in execute_workload
    supervise(
  File "/opt/airflow/task-sdk/src/airflow/sdk/execution_time/supervisor.py", line 2067, in supervise
    exit_code = process.wait()
  File "/opt/airflow/task-sdk/src/airflow/sdk/execution_time/supervisor.py", line 1040, in wait
    self.update_task_state_if_needed()
  File "/opt/airflow/task-sdk/src/airflow/sdk/execution_time/supervisor.py", line 1054, in update_task_state_if_needed
    self.client.task_instances.finish(
  File "/opt/airflow/task-sdk/src/airflow/sdk/api/client.py", line 228, in finish
    self.client.patch(f"task-instances/{id}/state", content=body.model_dump_json())
  File "/home/airflow/.local/lib/python3.10/site-packages/httpx/_client.py", line 1218, in patch
    return self.request(
  File "/home/airflow/.local/lib/python3.10/site-packages/tenacity/__init__.py", line 338, in wrapped_f
    return copy(f, *args, **kw)
  File "/home/airflow/.local/lib/python3.10/site-packages/tenacity/__init__.py", line 477, in __call__
    do = self.iter(retry_state=retry_state)
  File "/home/airflow/.local/lib/python3.10/site-packages/tenacity/__init__.py", line 378, in iter
    result = action(retry_state)
  File "/home/airflow/.local/lib/python3.10/site-packages/tenacity/__init__.py", line 400, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
  File "/usr/python/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/python/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.10/site-packages/tenacity/__init__.py", line 480, in __call__
    result = fn(*args, **kwargs)
  File "/opt/airflow/task-sdk/src/airflow/sdk/api/client.py", line 920, in request
    return super().request(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/httpx/_client.py", line 825, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/home/airflow/.local/lib/python3.10/site-packages/httpx/_client.py", line 914, in send
    response = self._send_handling_auth(
  File "/home/airflow/.local/lib/python3.10/site-packages/httpx/_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/home/airflow/.local/lib/python3.10/site-packages/httpx/_client.py", line 999, in _send_handling_redirects
    raise exc
  File "/home/airflow/.local/lib/python3.10/site-packages/httpx/_client.py", line 982, in _send_handling_redirects
    hook(response)
  File "/opt/airflow/task-sdk/src/airflow/sdk/api/client.py", line 182, in raise_on_4xx_5xx
    return get_json_error(response) or response.raise_for_status()
  File "/opt/airflow/task-sdk/src/airflow/sdk/api/client.py", line 178, in get_json_error
    raise err
airflow.sdk.api.client.ServerResponseError: Server returned error
```

**Comment by pdellarciprete** [comment]
Thanks a lot @ephraimbuddy to raise the PR, I will give it a try as soon as possible!

**Comment by kaxil** [comment]
@pdellarciprete Few questions:

1. Is this only happening for KE? (don't think so based on code-paths but want to confirm)
2. Could you upload logs from both schedulers when this happens? (full logs around the time of the race, not just excerpts)
3. What is your `scheduler_health_check_threshold` setting? And how long do your tasks typically take to execute?
4. In the Dec 15 logs showing the orphan reset - was Scheduler A actually unhealthy, or was it still running fine when Scheduler B marked its job as failed?


The `DagRun.get_running_dag_runs_to_examine()` uses `SELECT ... FOR UPDATE SKIP LOCKED` on DagRun rows. This means two schedulers should NOT be able to process the same DagRun concurrently - Scheduler B would skip any DagRun locked by Scheduler A:


```py
def get_running_dag_runs_to_examine(cls, session: Session) -> ScalarResult[DagRun]:
    """
    Return the next DagRuns that the scheduler should attempt to schedule.

    This will return zero or more DagRun rows that are row-level-locked with a "SELECT ... FOR UPDATE"
    query, you should ensure that any scheduling decisions are made in a single transaction -- as soon as
    the transaction is committed it will be unlocked.
    """
    ...
    return session.scalars(with_row_locks(query, of=cls, session=session, skip_locked=True)).unique()
```

Full Code: 

https://github.com/apache/airflow/blob/267a566e0488b6d91e3983ddd44fa507daa383db/airflow-core/src/airflow/models/dagrun.py#L581-L616

Given this, the `schedule_tis()` race (where two schedulers both increment try_number on the same TI) shouldn't be possible under normal operation.

**Comment by bohdan-pd** [comment]
Hi @ephraimbuddy I got the same error for MWAA environment. My task logic finished and XCom was pushed, but at the end I got this error. Could it be related?

```
AirflowRuntimeError: API_SERVER_ERROR: {'status_code': 409, 'message': 'Server returned error', 'detail': {'detail': {'reason': 'invalid_state', 'message': 'TI was not in the running state so it cannot be updated', 'previous_state': 'failed'}}}

File "/usr/local/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py", line 1351 in main

File "/usr/local/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py", line 999 in run

File "/usr/local/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/comms.py", line 204 in send

File "/usr/local/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/comms.py", line 264 in _get_response

File "/usr/local/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/comms.py", line 251 in _from_frame
```

**Comment by ephraimbuddy** [comment]
> Hi @ephraimbuddy I got the same error for MWAA environment. My task logic finished and XCom was pushed, but at the end I got this error. Could it be related?
> 
> ```
> AirflowRuntimeError: API_SERVER_ERROR: {'status_code': 409, 'message': 'Server returned error', 'detail': {'detail': {'reason': 'invalid_state', 'message': 'TI was not in the running state so it cannot be updated', 'previous_state': 'failed'}}}
> 
> File "/usr/local/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py", line 1351 in main
> 
> File "/usr/local/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py", line 999 in run
> 
> File "/usr/local/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/comms.py", line 204 in send
> 
> File "/usr/local/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/comms.py", line 264 in _get_response
> 
> File "/usr/local/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/comms.py", line 251 in _from_frame
> ```

It's similar to this: https://github.com/apache/airflow/pull/59650 but different from error on task start referenced for this issue

**Comment by bohdan-pd** [comment]
@ephraimbuddy I just got the same error mentioned in the issue. Thank you for working on this. I'm looking forward to the upcoming lifesaver fix 👍

**Comment by bohdan-pd** [comment]
@ephraimbuddy Would it be possible to backport fix into 3.0.6?

**Comment by pdellarciprete** [comment]
> [@pdellarciprete](https://github.com/pdellarciprete) Few questions:
> 
> 1. Is this only happening for KE? (don't think so based on code-paths but want to confirm)
> 2. Could you upload logs from both schedulers when this happens? (full logs around the time of the race, not just excerpts)
> 3. What is your `scheduler_health_check_threshold` setting? And how long do your tasks typically take to execute?
> 4. In the Dec 15 logs showing the orphan reset - was Scheduler A actually unhealthy, or was it still running fine when Scheduler B marked its job as failed?

Hello @kaxil , 

1. I noticed the issue only in our KE instances, so I'd say yes.
2. For the full logs I need to retrieve them, but I guess @ephraimbuddy, since he was able to reproduce it, he should have an example as well.
3. The `scheduler_health_check_threshold` is the default. 
4. The scheduler A was healthy, but probably the SchedulerJob heartbeat was too old and it was marked as failed.

**Comment by potiuk** [comment]
> @ephraimbuddy Would it be possible to backport fix into 3.0.6?

See https://github.com/apache/airflow/pull/59639#issuecomment-3691851849

**Comment by codecae** [comment]
for what it's worth, we have been experiencing what appears to be the identical race conditions when using the CeleryExecutor.  It doesn't appear that this is isolated to the k8s executor.

**Comment by ephraimbuddy** [comment]
Fixed in https://github.com/apache/airflow/pull/59639

**Comment by pdellarciprete** [comment]
Hello @ephraimbuddy ,

I tested the patch locally, and unfortunately is still happening in my case. I will wait the version `3.1.6.` to give it a try and see.

**Comment by ephraimbuddy** [comment]
> Hello @ephraimbuddy ,
> 
> I tested the patch locally, and unfortunately is still happening in my case. I will wait the version `3.1.6.` to give it a try and see. 

Can you share the task log you saw ? And confirm if there's try 1 & 2, visible in the UI. 

There's 3.1.6rc1 being voted, maybe you should try it?

**Comment by pdellarciprete** [comment]
Hello @ephraimbuddy, 
Immediately after the comment that I left I noticed there was the `3.1.6rc1` and I gave it a try, but unfortunately the issue for me is still there. 

[Here the example logs](https://github.com/user-attachments/files/24522871/scheduler_race_condition_example.json) and in the screenshot what I can see from the UI.

<img width="1842" height="572" alt="Image" src="https://github.com/user-attachments/assets/8e025a25-97b6-47af-a8b0-e45939477726" />

**Comment by ephraimbuddy** [comment]
@pdellarciprete , can you check if the TaskInstanceHistory table was updated for the first try?

**Comment by pdellarciprete** [comment]
Hello @ephraimbuddy, 

how should I check it? 
Looking into the DB I see :
```sql
SELECT * FROM
  "public"."task_instance"
  WHERE dag_id = 'sadp_dag_196'
  and run_id = 'scheduled__2026-01-09T00:15:00+00:00'
  and task_id = 'task_1';
```

```json
[
  {
    "task_id": "task_1",
    "dag_id": "sadp_dag_196",
    "run_id": "scheduled__2026-01-09T00:15:00+00:00",
    "map_index": "-1",
    "start_date": "2026-01-09T01:24:48.581784Z",
    "end_date": "2026-01-09T01:25:02.241058Z",
    "duration": "13.659274",
    "state": "success",
    "try_number": "2",
    "max_tries": "3",
    "hostname": "sadp-dag-196-task-1-sh6ds4u1",
    "unixname": "airflow",
    "pool": "default_pool",
    "pool_slots": "1",
    "queue": "default",
    "priority_weight": "5",
    "operator": "PythonOperator",
    "custom_operator_name": "PythonOperator",
    "queued_dttm": "2026-01-09T01:22:54.77853Z",
    "queued_by_job_id": "21663",
    "pid": "14",
    "executor_config": "\u0005}.",
    "updated_at": "2026-01-09T01:25:11.016781Z",
    "rendered_map_index": "",
    "external_executor_id": "21661",
    "trigger_id": "",
    "trigger_timeout": "",
    "next_method": "",
    "next_kwargs": "null",
    "task_display_name": "task_1",
    "executor": "",
    "id": "019ba053-04d0-7b93-9d66-bd0c7d821b46",
    "last_heartbeat_at": "2026-01-09T01:25:02.260657Z",
    "dag_version_id": "019b1df2-dde1-7d84-a2db-c654784fba00",
    "scheduled_dttm": "2026-01-09T01:22:54.618276Z",
    "context_carrier": "",
    "span_status": "ended"
  }
]
```

**Comment by ephraimbuddy** [comment]
I have created another PR to deal specifically with the log you got. Can you try it: https://github.com/apache/airflow/pull/60330. If it fixes it, then if there's 3.1.6rc2 we will include it. 

From the log scheduler_race_condition_example.json:

- 01:21:46 Scheduler pod A enqueues the TI as try 1:
  "2026-01-09T01:21:46.380591Z [info     ] Add task TaskInstanceKey(dag_id='sadp_dag_196', task_id='task_1',...try_number=1,...

- 01:22:54 Scheduler pod B enqueues the same TI again as try 2:
  "2026-01-09T01:22:54.802854Z [info     ] Add task TaskInstanceKey(dag_id='sadp_dag_196', task_id='task_1', ..., try_number=2,...

This second enqueue happens before any worker starts (the first worker “Executing workload” line is 01:24:48), so the try bump is happening purely in scheduler logic.

Then:

-  01:24:48 → 01:25:03 the worker runs try 2 and the Execution API marks the TI success.

- 01:26:30 a worker pod later starts try 1, but the API rejects it:
      Cannot start Task Instance in invalid state ... previous_state=success
      /run ... 409 Conflict

This happened because DagRun.schedule_tis() updated rows using only TI.id.in_(...). In HA, scheduler B can have a stale in-memory view that still treats the TI as schedulable, run schedule_tis(), and increment try_number even if scheduler A has already advanced the TI.

I reproduced it in unit tests. However, please try it in your deployment.

> how should I check it?

The case you saw is different from adoption so it won't record in TI history. The adoption case which was fixed happens only when a scheduler is marked failed and another scheduler unable to adopt the task, resets it. If you want to check if there are cases like that in your deployment, you can `select * from task_instance_history where dag_id=...`

**Comment by pdellarciprete** [comment]
I am gonna try it, I'll keep you posted

**Comment by pdellarciprete** [comment]
Hello @ephraimbuddy , 

bad news, I tested it and I can still see the issue :/

**Comment by ephraimbuddy** [comment]
> Hello @ephraimbuddy , 
> 
> bad news, I tested it and I can still see the issue :/ 

Can you share the logs again

**Comment by pdellarciprete** [comment]
[Here](https://github.com/user-attachments/files/24533534/Logs-2026-01-09.19_43_13.json) are the new logs.

**Comment by ephraimbuddy** [comment]
> [Here](https://github.com/user-attachments/files/24533534/Logs-2026-01-09.19_43_13.json) are the new logs.

Open a python shell in the scheduler pods and let me know what you get when you run the below:
```python
import inspect
import airflow.models.dagrun as dagrun
path = inspect.getsourcefile(dagrun)
print("dagrun.py", path)
txt = open(path, "r", encoding="utf-8").read()
print("Has guards: ", "schedulable_state_clause" in txt and "non_null_schedulable_states" in txt)
```
It's just to be sure it was patched well

**Comment by pdellarciprete** [comment]
Here it is:

<img width="763" height="325" alt="Image" src="https://github.com/user-attachments/assets/90698b3f-86f0-439d-922f-57a403860d0e" />

**Comment by ephraimbuddy** [comment]
Long chase :). Reproduced in main without the fix:

<img width="735" height="474" alt="Image" src="https://github.com/user-attachments/assets/575e0e22-2e86-49d7-8b4e-edc8a652a31a" />

**Comment by pdellarciprete** [comment]
Hi @phanikumv,
I noticed that @ephraimbuddy removed the assignment. Is there any chance we could still address the issue described here?

**Comment by bohdan-pd** [comment]
Any workaround here, please?

**Comment by phanikumv** [comment]
@ephraimbuddy can you provide the steps to reproduce the issue, so that others from the community can pick it?

**Comment by ephraimbuddy** [comment]
> [@ephraimbuddy](https://github.com/ephraimbuddy) can you provide the steps to reproduce the issue, so that others from the community can pick it?

The reproduction is not reliable. When I reproduced it, I ran 4 schedulers & 2 api-servers and ran this dag in a kubernetes cluster:
```python
import time
from datetime import datetime
from airflow import DAG
from airflow.operators.python import PythonOperator

def hello_world():
    print("Doing my job...")
    time.sleep(10)
    print("Job done!")

def create_dag(dag_id):
    with DAG(
        dag_id=dag_id,
        schedule="15 */1 * * *",
        start_date=datetime(2025, 1, 1),
        catchup=False,
        tags=["test:sadp_environment"],
    ) as dag:

        previous = None
        for i in range(1, 6):
            t = PythonOperator(
                task_id=f"task_{i}",
                python_callable=hello_world,
            )
            if previous:
                previous >> t
            previous = t

        return dag


# Register 100 DAGs
for n in range(1, 500):
    dag_id = f"sadp_dag_{n}"
    globals()[dag_id] = create_dag(dag_id)
```

After some hours, I searched for the issue in the db:

```sql
SELECT ti.dag_id, ti.task_id, ti.run_id
FROM task_instance ti
WHERE ti.try_number = 2
  AND NOT EXISTS (
    SELECT 1
    FROM task_instance_history tih
    WHERE tih.dag_id = ti.dag_id
      AND tih.task_id = ti.task_id
      AND tih.run_id = ti.run_id
      AND tih.map_index = ti.map_index
      AND tih.try_number = 1
  );
```

On subsequent, runs, I couldn't reproduce it again
