### ISSUE TITLE
Display Username in the UI

### ISSUE THREAD

**Issue by alkismavridis** [apache/airflow#58618]
### Description

I apologise in advance if I miss something, but in airflow 3 I can see nowhere the user that I am currently logged in as.
I often switch between users, so it would be important to know that I am logged in with the current one.

In airflow 2 there was this bubble on the top right corner: 

<img width="2994" height="1740" alt="Image" src="https://github.com/user-attachments/assets/2bb2f1ff-d005-49e9-a482-a782ab35d967" />

But in airflow 3 I cannot see it anywhere:

<img width="603" height="868" alt="Image" src="https://github.com/user-attachments/assets/3809a573-1444-42ca-b3c7-43f99542006d" />

### Use case/motivation

Being able to view who am I logged in as.

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR! (at least I would happily try)

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by aaron-wolmutt** [comment]
@vincbeck @potiuk I can take this one as a follow up to #58292 if you want to assign me

**Comment by vincbeck** [comment]
Done

**Comment by alkismavridis** [comment]
Hello @pierrejeambrun. Sorry for the late reply here. I just upgraded to 3.1.6 but still do not see my user. Do I miss something?

<img width="370" height="330" alt="Image" src="https://github.com/user-attachments/assets/bfa9f347-b50f-4c75-a40d-4d64e2b6b34a" />



<img width="270" height="181" alt="Image" src="https://github.com/user-attachments/assets/6acf967a-a882-4309-9859-12974e089881" />


Thanks in advance 🙏

**Comment by pierrejeambrun** [comment]
Hello @alkismavridis,

This was marked as a new feature and targetted for `3.2.0`. So this is not released yet and we need to wait for next minor version to come up. (3.2.0 is planned around mid march)

**Comment by aaronfenstermacher** [comment]
What was actually added with this? The username, e-mail, or DB UID? We have a few end-users asking for e-mail to be 'added back' after upgrading to AF3. I'll look for a request for specifically that but found this first.
