### ISSUE TITLE
DagBundle Import Error Detected but Not Displayed in UI

### ISSUE THREAD

**Issue by carlos54** [apache/airflow#59272]
### Apache Airflow version

Other Airflow 2/3 version (please specify below)

### If "Other Airflow 2/3 version" selected, which one?

3.1.4

### What happened?

Description :
The Dag Processor correctly identifies and logs an import error within a DAG file, but the corresponding error message and Stack Trace are not visible in the Airflow User Interface (no "import Errors" tab).

```
DAG File Processing Stats
Bundle File Path PID Current Duration # DAGs # Errors Last Duration Last Run At
-------- ---------------------------------- ----- ------------------ -------- ---------- --------------- -------------------
sandbox sandbox_dag005_dataset_producer.py 1 0 0.26s 2025-12-10T11:38:29
sandbox sandbox_dag_demo.py 0 1 0.21s 2025-12-10T11:38:29
```

 Error in log dag processor log file are correctly catch :

```
{"timestamp":"2025-12-10T11:33:23.270722Z","level":"error","event":"AirflowException(\"Task Policy validation failed for 'DO_DATASET':\\n[DATASET OUTLETS] Dataset URI 'event_data01_dispo' in
 task 'DO_DATASET' must start with 'sandbox_'.\")","logger":"airflow.models.dagbag.DagBag","filename":"dagbag.py","lineno":556,"error_detail":[{"exc_type":"AirflowException","exc_value":"Tas
k Policy validation failed for 'DO_DATASET':\n[DATASET OUTLETS] Dataset URI 'event_data01_dispo' in task 'DO_DATASET' must start with 'sandbox_'.","exc_notes":[],"syntax_error":null,"is_caus
e":false,"frames":[{"filename":"/usr/local/lib/python3.12/site-packages/airflow/models/dagbag.py","lineno":552,"name":"bag_dag"},{"filename":"/usr/local/lib/python3.12/site-packages/airflow/settings.py","lineno":183,"name":"task_policy"},{"filename":"/usr/local/lib/python3.12/site-packages/pluggy/_hooks.py","lineno":512,"name":"__call__"},{"filename":"/usr/local/lib/python3.12/site-packages/pluggy/_manager.py","lineno":120,"name":"_hookexec"},{"filename":"/usr/local/lib/python3.12/site-packages/pluggy/_callers.py","lineno":167,"name":"_multicall"},{"filename":"/usr/local/lib/python3.12/site-packages/pluggy/_callers.py","lineno":121,"name":"_multicall"},{"filename":"/opt/airflow/config/cluster_policy.py","lineno":173,"name":"task_policy"}],"is_group":false,"exceptions":[]}]}
```

This prevents developers from quickly identifying the source of the failure, especially those caused by the cluster_policy.

### What you think should happen instead?

The "Import Errors" view in the Airflow UI should be display .

### How to reproduce

  The dag_processor ariflow.cfg:
    dag_bundle_config_list: '{{ .Values.DAGS.bundle_list }}' 
    dag_bundle_storage_path: '/dags/airflow/bundles' 
    refresh_interval: 60
    bundle_refresh_check_interval : 15
    print_stats_interval: 60
    parsing_processes: 2
    dag_file_processor_timeout: 60
    min_file_process_interval: 30
    stale_dag_threshold : 300

### Operating System

redhat/ubi9:9.6

### Versions of Apache Airflow Providers

apache-airflow==3.1.4 \
structlog==25.5.0 \
psycopg2-binary==2.9.11 \
asyncpg==0.31.0 \
apache-airflow-providers-fab==3.0.3 \
apache-airflow-providers-redis==4.4.0 \
apache-airflow-providers-git==0.1.0 \
apache-airflow-providers-cncf-kubernetes==10.11.0 \
flask-limiter==3.12 \
redis==5.3.1 \
authlib==1.6.5 \
PyJWT==2.10.1 \
cryptography==42.0.8 \
requests==2.32.5

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bil-ly** [comment]
@potiuk @carlos54  I can look into this

**Comment by carlos54** [comment]
Thanks! Because without UI feedback, a developer cannot know what is wrong with their DAG.

**Comment by potiuk** [comment]
> [@potiuk](https://github.com/potiuk) [@carlos54](https://github.com/carlos54) I can look into this

Please @bil-ly  don't mention people who might or might not be related to the issue/ PR - if you want to be assigned just mention it in the comment - and **someone** will assign you - it does not have to be me.

**Comment by carlos54** [comment]
airflow config list

`
[core]
dags_folder = /opt/airflow/dags
hostname_callable = airflow.utils.net.getfqdn
might_contain_dag_callable = airflow.utils.file.might_contain_dag_via_default_heuristic
default_timezone = Europe/Paris
executor = KubernetesExecutor
auth_manager = airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
simple_auth_manager_users = admin:admin
simple_auth_manager_all_admins = False
parallelism = 5
max_active_tasks_per_dag = 2
dags_are_paused_at_creation = True
max_active_runs_per_dag = 1
max_consecutive_failed_dag_runs_per_dag = 0
load_examples = False
plugins_folder = /opt/airflow/plugins
execute_tasks_new_python_interpreter = False
fernet_key = <FERNET_KEY_MASKED>
dagbag_import_timeout = 30.0
dagbag_import_error_tracebacks = True
dagbag_import_error_traceback_depth = 10
default_impersonation =
security =
unit_test_mode = False
allowed_deserialization_classes = airflow.*
allowed_deserialization_classes_regexp =
killed_task_cleanup_time = 60
dag_run_conf_overrides_params = True
dag_discovery_safe_mode = True
dag_ignore_file_syntax = glob
default_task_retries = 0
default_task_retry_delay = 300
max_task_retry_delay = 86400
default_task_weight_rule = downstream
task_success_overtime = 20
default_task_execution_timeout =
min_serialized_dag_update_interval = 30
compress_serialized_dags = False
min_serialized_dag_fetch_interval = 10
max_num_rendered_ti_fields_per_task = 30
xcom_backend = airflow.sdk.execution_time.xcom.BaseXCom
lazy_load_plugins = false
lazy_discover_providers = True
hide_sensitive_var_conn_fields = True
sensitive_var_conn_names =
default_pool_task_slot_count = 128
max_map_length = 1024
daemon_umask = 0o077
test_connection = Disabled
max_templated_field_length = 4096
execution_api_server_url = http://airflow-api-server:8080/execution/
colored_console_log = False
fernet_key_cmd = cat /vault/secrets/fernet-key
remote_logging = False

[database]
alembic_ini_file_path = alembic.ini
sql_alchemy_conn = postgresql+psycopg2://proxy_user:***@db-proxy.internal:6432/airflow_db
sql_engine_encoding = utf-8
sql_alchemy_pool_enabled = true
sql_alchemy_pool_size = 5
sql_alchemy_max_overflow = 10
sql_alchemy_pool_recycle = 1800
sql_alchemy_pool_pre_ping = true
max_db_retries = 3
check_migrations = True
migration_batch_size = 10000

[logging]
base_log_folder = /opt/airflow/logs
remote_logging = false
logging_level = DEBUG
logging_config_class =
colored_console_log = False
log_format =
simple_log_format = %%(asctime)s %%(levelname)s - %%(message)s
dag_processor_log_target = file
log_formatter_class = airflow.utils.log.timezone_aware.TimezoneAware
min_length_masked_secret = 5
task_log_prefix_template =
log_filename_template = dag_id={{ ti.dag_id }}/run_id={{ ti.run_id }}/task_id={{ ti.task_id }}/{%% if ti.map_index >= 0 %%}map_index={{ ti.map_index }}/{%% endif %%}attempt={{ try_number|default(ti.try_number) }}.log
task_log_reader = task
file_task_handler_new_folder_permissions = 0o775
file_task_handler_new_file_permissions = 0o664

[api]
enable_swagger_ui = True
secret_key = <API_SECRET_MASKED>
expose_config = False
expose_stacktrace = true
base_url = https://airflow.internal
host = 0.0.0.0
port = 8080
workers = 1
worker_timeout = 120
maximum_page_limit = 100
fallback_page_limit = 50
grid_view_sorting_order = topological
log_fetch_timeout_sec = 5
hide_paused_dags_by_default = False
page_size = 50
auto_refresh_interval = 3
secret_key_cmd = cat /vault/secrets/webserver-key

[api_auth]
jwt_expiration_time = 86400
jwt_cli_expiration_time = 3600
jwt_secret = cat /vault/secrets/webserver-key
algorithm = RS256
audience = https://api.internal/api/v2
issuer = https://api-stg.internal
jwks_url = https://auth.internal/sps/jwks

[smtp]
smtp_host = mail-relay.internal
smtp_starttls = true
smtp_ssl = false
smtp_port = 25
smtp_mail_from = noreply@internal
smtp_timeout = 30
smtp_retry_limit = 5
smtp_password = cat /vault/secrets/smtp-password
smtp_user = noreply@internal

[kubernetes]
namespace = airflow-prod
worker_container_repository = registry.internal/airflow
worker_container_tag = 0.0.1
delete_worker_pods = True
multi_namespace_mode = true
in_cluster = True

[webserver]
rbac = True
enable_proxy_fix = True



`

**Comment by carlos54** [comment]
FYI
The Airflow table in database shows no errors despite the DAG processing failure.:

 ./logs/dag_processor/latest/sandbox/sandbox_base_test_error.py.log :

`
{"timestamp":"2026-01-27T14:21:01.795727Z","level":"error","event":"Failed to import: /dags/airflow/bundles/sandbox/tracking_repo/sandbox_base_test_error.py","logger":"airflow.models.dagbag.DagBag","filename":"dagbag.py","lineno":415,"error_detail":[{"exc_type":"SyntaxError","exc_value":"invalid syntax. Perhaps you forgot a comma? (sandbox_base_test_error.py, line 63)","exc_notes":[],"syntax_error":{"offset":25,"filename":"/dags/airflow/bundles/sandbox/tracking_repo/sandbox_base_test_error.py","line":"...
`



`
SELECT * FROM import_error;
id | timestamp | filename | bundle_name | stacktrace
----+-----------+----------+-------------+------------
(0 rows)
`

**Comment by uplsh580** [comment]
Is there any ongoing work on this issue?
I'd like to distribute a fixed version to our organization.
If not, can I fix it myself?
I'm asking cautiously, as there's already an assignee.

**Comment by bil-ly** [comment]
@uplsh580 you can take a look at it, i hadn't realised(didn't get notification email) , i hadn't done a lot , so you can implement the fix

**Comment by uplsh580** [comment]
This issue seems to be occurring in `LocalDagBundle` as well.

<img width="979" height="390" alt="Image" src="https://github.com/user-attachments/assets/2ec51b71-c392-4f56-89c3-1030a4766485" />

<img width="1230" height="542" alt="Image" src="https://github.com/user-attachments/assets/a801206e-56f3-4aee-b74c-48e4d1d0cf9c" />
<img width="1840" height="921" alt="Image" src="https://github.com/user-attachments/assets/7ebff6f1-6c0c-4373-984d-861ac5f65ce7" />
<img width="1896" height="855" alt="Image" src="https://github.com/user-attachments/assets/f46cc687-4041-4e5d-9b34-9365d0da5c7f" />

**Comment by uplsh580** [comment]
Gitbundle is also not visible

<img width="1453" height="847" alt="Image" src="https://github.com/user-attachments/assets/625128cf-f852-473e-9963-d9b796400901" />
<img width="1814" height="948" alt="Image" src="https://github.com/user-attachments/assets/0aba2083-348c-4a4b-9090-4408357eccff" />
<img width="1894" height="929" alt="Image" src="https://github.com/user-attachments/assets/4ec61e8c-51f2-481c-b259-c83a277c07ef" />

**Comment by uplsh580** [comment]
This was fixed in PR #61163.

**Comment by rodrigoassumpcao** [comment]
> This was fixed in PR [#61163](https://github.com/apache/airflow/pull/61163).

Hi @uplsh580. I think the problem persists in 3.1.7 (PR #61163 version)

I updated to the latest version (3.1.7) and the problem persists. The PR only change the import_error api route... The database table import_error still empty.

**Comment by rodrigoassumpcao** [comment]
Hi guys.

I'm not an expert with the Airflow source code, but it seems that a commit/flush is missing after a `session.add` in the `_update_import_errors` method of collection.py file.

I added a `session.flush()` after line 342 in `airflow/dag_processing/collection.py` file and the `import_error` table starts being populated.

Here is the version I used: https://github.com/apache/airflow/blob/3.1.7/airflow-core/src/airflow/dag_processing/collection.py

**Comment by uplsh580** [comment]
> > This was fixed in PR [#61163](https://github.com/apache/airflow/pull/61163).
> 
> Hi @uplsh580. I think the problem persists in 3.1.7 (PR #61163 version)
> 
> I updated to the latest version (3.1.7) and the problem persists. The PR only change the import_error api route... The database table import_error still empty.

@rodrigoassumpcao 
I previously verified the fix using Breeze and it seemed to be working at the time, but I’ll take another look into why the table is still empty in version 3.1.7.

**Comment by uplsh580** [comment]
@rodrigoassumpcao
It seems there were several complex factors involved. I've confirmed that the issue is now resolved on the latest `main` branch (breeze option: Celery Executor, python 3.11, mysql backend). The ImportError related to gitbundle is correctly displayed on the UI. 
<img width="1486" height="869" alt="Image" src="https://github.com/user-attachments/assets/30d9c768-f05c-4088-ab75-69aaf53f4b5c" />
