### ISSUE TITLE
providers-fab: Airflow 3.1.3 sqlalchemy.exc.PendingRollbackError: Can't reconnect until invalid transaction is rolled back

### ISSUE THREAD

**Issue by berglh** [apache/airflow#59349]
### Apache Airflow Provider(s)

fab

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon==9.16.0
apache-airflow-providers-apache-spark==5.4.0
apache-airflow-providers-celery==3.13.0
apache-airflow-providers-cncf-kubernetes==10.11.0
apache-airflow-providers-common-compat==1.10.0
apache-airflow-providers-common-io==1.6.4
apache-airflow-providers-common-messaging==2.0.0
apache-airflow-providers-common-sql==1.28.2
apache-airflow-providers-docker==4.4.4
apache-airflow-providers-elasticsearch==6.3.4
apache-airflow-providers-fab==3.0.3
apache-airflow-providers-ftp==3.13.2
apache-airflow-providers-git==0.0.9
apache-airflow-providers-google==18.1.0
apache-airflow-providers-grpc==3.8.2
apache-airflow-providers-hashicorp==4.3.3
apache-airflow-providers-http==5.4.0
apache-airflow-providers-microsoft-azure==12.8.0
apache-airflow-providers-mysql==6.3.4
apache-airflow-providers-odbc==4.10.2
apache-airflow-providers-openlineage==2.7.3
apache-airflow-providers-postgres==6.4.0
apache-airflow-providers-redis==4.3.2
apache-airflow-providers-sendgrid==4.1.4
apache-airflow-providers-sftp==5.4.1
apache-airflow-providers-slack==9.4.0
apache-airflow-providers-smtp==2.3.1
apache-airflow-providers-snowflake==6.6.0
apache-airflow-providers-ssh==4.1.5
apache-airflow-providers-standard==1.10.0

### Apache Airflow version

3.1.3

### Operating System

Amazon Linux 2023

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

EKS v1.33
Airflow Chart 1.18.0
Aurora Postgres 16.9
Replicas 2 of every component
Have three roles and users (admin, group1, group 2)

### What happened

I'm receiving the same errors mentioned in the following issues, despite running version 3.0.3 of the FAB provider. The login works for several days before failing with the error:

```
2025-12-11T23:56:28.992968Z [error    ] Exception on /login/ [GET]     [airflow.providers.fab.www.app] loc=app.py:1744
Traceback (most recent call last)
...
 raise exc.PendingRollbackError(
sqlalchemy.exc.PendingRollbackError: Can't reconnect until invalid transaction is rolled back. (Background on this error at: https://sqlalche.me/e/14/8s2b)
```

- https://github.com/apache/airflow/issues/57470
- https://github.com/apache/airflow/issues/57859

### Stacktrace
[airflow-api-error.log](https://github.com/user-attachments/files/24119119/airflow-api-error.log)

### What you think should happen instead

Ideally, the sqlAlchemy error shouldn't occur.

### How to reproduce

Run FAB with in-built user authentication for several days and wait for the error to appear.

### Anything else

I'm wondering if the issue may be resulted to running API replicas and hitting some irrecoverable lock state of some kind.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by keshan17** [comment]
we're also having the same issue even updating the latest versions.

**Comment by ovintuan** [comment]
I also have the same issue, can see that this error can be reproduce by action with new login into Airflow (may by any times) then they will have this issue after along times (hours). You still keep the session with old cookies.

---> I must restart my API-Server for my team for new login. I meet this issues from fab 3.0.1 to 3.0.3.

**Comment by rmalai-amdaris** [comment]
Confirming I'm seeing the same issue at my end. Steps to reproduce: stay logged in and re-access the airflow after one day. It will usually error out with this error.

**Comment by ryan-dyer-sp** [comment]
Same problem here.

**Comment by alex-brunshtein** [comment]
Same problem with:
- apache-airflow 3.1.5
- apache-airflow-providers-fab 3.1.0

Problem started after:
- apache-airflow 3.0.6
- apache-airflow-providers-fab 2.4.1

**Comment by vincbeck** [comment]
Can someone please try these fixes:

```
[database]
sql_alchemy_pool_pre_ping = True

[fab]
session_lifetime_minutes = 1440
```

I would like to see if these config changes fix the issue. If yes, I'll create a PR to change the default value of these configs

**Comment by berglh** [comment]
@vincbeck I've made the changes as per your suggestion, I will have my team keep an eye on it and let you know.

> ```
> [database]
> sql_alchemy_pool_pre_ping = True
> 
> [fab]
> session_lifetime_minutes = 1440
> ```

**Comment by vincbeck** [comment]
> [@vincbeck](https://github.com/vincbeck) I've made the changes as per your suggestion, I will have my team keep an eye on it and let you know.
> 
> > ```
> > [database]
> > sql_alchemy_pool_pre_ping = True
> > 
> > [fab]
> > session_lifetime_minutes = 1440
> > ```

Thank you!

**Comment by alex-brunshtein** [comment]
> Can someone please try these fixes:

I try it

**Comment by rmalai-amdaris** [comment]
> Can someone please try these fixes:
> 
> ```
> [database]
> sql_alchemy_pool_pre_ping = True
> 
> [fab]
> session_lifetime_minutes = 1440
> ```
> 
> I would like to see if these config changes fix the issue. If yes, I'll create a PR to change the default value of these configs

I'm already on the pre-ping settings. The new thing which is shown here is the session lifetime. Doesn't fix the issue.
```
  # SQLAlchemy engine options for both Airflow database and Celery result backend
  # Optimized for RDS Proxy with TCP keepalive and connection recycling
  sqlalchemy_engine_options = jsonencode({
    pool_size            = 5
    pool_recycle         = var.proxy_idle_client_timeout - 100 # 1700s (100s before proxy timeout)
    pool_pre_ping        = true                                # Test connections on checkout
    pool_reset_on_return = "rollback"                          # Auto-rollback failed transactions on connection return
  })
}
```

**Comment by alex-brunshtein** [comment]
> Can someone please try these fixes:
> 
> ```
> [database]
> sql_alchemy_pool_pre_ping = True
> 
> [fab]
> session_lifetime_minutes = 1440
> ```

It doesn't work. After 15 minutes from pod starting and logon, I get an error for any menu in Security. This has been happening since Airflow 3.1.x.
I use k8s, Airflow Chart 1.18.0, Airflow 3.1.5, apache-airflow-providers-fab 3.1.0, standalone postgres 16)

```
INFO:     10.128.4.95:40536 - "GET /api/v2/version HTTP/1.1" 200 OK
INFO:     10.128.4.95:40538 - "GET /api/v2/version HTTP/1.1" 200 OK
INFO:     10.128.4.95:49450 - "GET /api/v2/version HTTP/1.1" 200 OK
INFO:     10.128.4.95:49448 - "GET /api/v2/version HTTP/1.1" 200 OK
INFO:     10.128.4.95:35822 - "GET /api/v2/version HTTP/1.1" 200 OK
INFO:     10.128.4.95:35818 - "GET /api/v2/version HTTP/1.1" 200 OK
INFO:     10.128.13.247:56794 - "GET /security/users HTTP/1.1" 200 OK
INFO:     10.128.13.247:56794 - "GET /ui/config HTTP/1.1" 200 OK
INFO:     10.128.13.247:56794 - "GET /ui/auth/menus HTTP/1.1" 200 OK
INFO:     10.128.13.247:56794 - "GET /api/v2/version HTTP/1.1" 200 OK
INFO:     10.128.13.247:56802 - "GET /api/v2/plugins HTTP/1.1" 200 OK
2025-12-16T09:22:54.105673Z [error    ] Exception on /users/list/ [GET] [airflow.providers.fab.www.app] loc=app.py:1744
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.OperationalError: SSL connection has been closed unexpectedly
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/flask/app.py", line 1821, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/flask/app.py", line 2313, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/fab/www/security_manager.py", line 57, in before_request
    g.user = get_auth_manager().get_user()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/fab/auth_manager/fab_auth_manager.py", line 282, in get_user
    if current_user.is_anonymous and getattr(g, "user", None) is not None and not g.user.is_anonymous:
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/werkzeug/local.py", line 316, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/werkzeug/local.py", line 520, in _get_current_object
    return get_name(local())  # type: ignore
                    ^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/flask_login/utils.py", line 25, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
                                      ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/flask_login/utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
  File "/home/airflow/.local/lib/python3.12/site-packages/flask_login/login_manager.py", line 364, in _load_user
    user = self._user_callback(user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/fab/auth_manager/security_manager/override.py", line 1396, in load_user
    user = self.get_user_by_id(int(pk))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/fab/auth_manager/security_manager/override.py", line 1402, in get_user_by_id
    return self.session.get(self.user_model, pk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1717, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) SSL connection has been closed unexpectedly
[SQL: SELECT ab_user.id AS ab_user_id, ab_user.first_name AS ab_user_first_name, ab_user.last_name AS ab_user_last_name, ab_user.username AS ab_user_username, ab_user.password AS ab_user_password, ab_user.active AS ab_user_active, ab_user.email AS ab_user_email, ab_user.last_login AS ab_user_last_login, ab_user.login_count AS ab_user_login_count, ab_user.fail_login_count AS ab_user_fail_login_count, ab_user.created_on AS ab_user_created_on, ab_user.changed_on AS ab_user_changed_on, ab_user.created_by_fk AS ab_user_created_by_fk, ab_user.changed_by_fk AS ab_user_changed_by_fk 
FROM ab_user 
WHERE ab_user.id = %(pk_1)s]
[parameters: {'pk_1': 5}]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
INFO:     10.128.13.247:56802 - "GET /auth/users/list/ HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
  + Exception Group Traceback (most recent call last):
  |   File "/home/airflow/.local/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/home/airflow/.local/lib/python3.12/site-packages/fastapi/applications.py", line 1082, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/applications.py", line 113, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
  |     raise exc
  |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
  |     await self.app(scope, receive, _send)
  |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/middleware/gzip.py", line 29, in __call__
  |     await responder(scope, receive, send)
  |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/middleware/gzip.py", line 130, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/middleware/gzip.py", line 46, in __call__
  |     await self.app(scope, receive, self.send_with_compression)
  |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/middleware/cors.py", line 85, in __call__
  |     await self.app(scope, receive, send)
  |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 189, in __call__
  |     raise app_exc
  |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 144, in coro
  |     await self.app(scope, receive_or_disconnect, send_no_error)
  |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 63, in __call__
  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |     raise exc
  |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/routing.py", line 716, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/routing.py", line 736, in app
  |     await route.handle(scope, receive, send)
  |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/routing.py", line 462, in handle
  |     await self.app(scope, receive, send)
  |   File "/home/airflow/.local/lib/python3.12/site-packages/fastapi/applications.py", line 1082, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/applications.py", line 113, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
  |     raise exc
  |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
  |     await self.app(scope, receive, _send)
  |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 63, in __call__
  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |     raise exc
  |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/routing.py", line 716, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/routing.py", line 736, in app
  |     await route.handle(scope, receive, send)
  |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/routing.py", line 462, in handle
  |     await self.app(scope, receive, send)
  |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/middleware/wsgi.py", line 81, in __call__
  |     await responder(receive, send)
  |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/middleware/wsgi.py", line 106, in __call__
  |     async with anyio.create_task_group() as task_group:
  |                ^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/home/airflow/.local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 783, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    |     self.dialect.do_execute(
    |   File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    |     cursor.execute(statement, parameters)
    | psycopg2.OperationalError: SSL connection has been closed unexpectedly
    | 
    | 
    | The above exception was the direct cause of the following exception:
    | 
    | Traceback (most recent call last):
    |   File "/home/airflow/.local/lib/python3.12/site-packages/flask/app.py", line 2529, in wsgi_app
    |     response = self.full_dispatch_request()
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/flask/app.py", line 1825, in full_dispatch_request
    |     rv = self.handle_user_exception(e)
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/flask/app.py", line 1821, in full_dispatch_request
    |     rv = self.preprocess_request()
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/flask/app.py", line 2313, in preprocess_request
    |     rv = self.ensure_sync(before_func)()
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/fab/www/security_manager.py", line 57, in before_request
    |     g.user = get_auth_manager().get_user()
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/fab/auth_manager/fab_auth_manager.py", line 282, in get_user
    |     if current_user.is_anonymous and getattr(g, "user", None) is not None and not g.user.is_anonymous:
    |        ^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/werkzeug/local.py", line 316, in __get__
    |     obj = instance._get_current_object()
    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/werkzeug/local.py", line 520, in _get_current_object
    |     return get_name(local())  # type: ignore
    |                     ^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/flask_login/utils.py", line 25, in <lambda>
    |     current_user = LocalProxy(lambda: _get_user())
    |                                       ^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/flask_login/utils.py", line 370, in _get_user
    |     current_app.login_manager._load_user()
    |   File "/home/airflow/.local/lib/python3.12/site-packages/flask_login/login_manager.py", line 364, in _load_user
    |     user = self._user_callback(user_id)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/fab/auth_manager/security_manager/override.py", line 1396, in load_user
    |     user = self.get_user_by_id(int(pk))
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/fab/auth_manager/security_manager/override.py", line 1402, in get_user_by_id
    |     return self.session.get(self.user_model, pk)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    |     return self._get_impl(
    |            ^^^^^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    |     return db_load_fn(
    |            ^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    |     session.execute(
    |   File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1717, in execute
    |     result = conn._execute_20(statement, params or {}, execution_options)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20
    |     return meth(self, args_10style, kwargs_10style, execution_options)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    |     return connection._execute_clauseelement(
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    |     ret = self._execute_context(
    |           ^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    |     self._handle_dbapi_exception(
    |   File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    |     util.raise_(
    |   File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    |     raise exception
    |   File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    |     self.dialect.do_execute(
    |   File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    |     cursor.execute(statement, parameters)
    | sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) SSL connection has been closed unexpectedly
    | 
    | [SQL: SELECT ab_user.id AS ab_user_id, ab_user.first_name AS ab_user_first_name, ab_user.last_name AS ab_user_last_name, ab_user.username AS ab_user_username, ab_user.password AS ab_user_password, ab_user.active AS ab_user_active, ab_user.email AS ab_user_email, ab_user.last_login AS ab_user_last_login, ab_user.login_count AS ab_user_login_count, ab_user.fail_login_count AS ab_user_fail_login_count, ab_user.created_on AS ab_user_created_on, ab_user.changed_on AS ab_user_changed_on, ab_user.created_by_fk AS ab_user_created_by_fk, ab_user.changed_by_fk AS ab_user_changed_by_fk 
    | FROM ab_user 
    | WHERE ab_user.id = %(pk_1)s]
    | [parameters: {'pk_1': 5}]
    | (Background on this error at: https://sqlalche.me/e/14/e3q8)
    | 
    | During handling of the above exception, another exception occurred:
    | 
    | Traceback (most recent call last):
    |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/middleware/wsgi.py", line 109, in __call__
    |     await anyio.to_thread.run_sync(self.wsgi, environ, self.start_response)
    |   File "/home/airflow/.local/lib/python3.12/site-packages/anyio/to_thread.py", line 61, in run_sync
    |     return await get_async_backend().run_sync_in_worker_thread(
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2525, in run_sync_in_worker_thread
    |     return await future
    |            ^^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 986, in run
    |     result = context.run(func, *args)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/middleware/wsgi.py", line 147, in wsgi
    |     for chunk in self.app(environ, start_response):
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/flask/app.py", line 2552, in __call__
    |     return self.wsgi_app(environ, start_response)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
    |     return self.app(environ, start_response)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/flask/app.py", line 2532, in wsgi_app
    |     response = self.handle_exception(e)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/flask/app.py", line 1727, in handle_exception
    |     server_error = self.ensure_sync(handler)(server_error)
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/fab/www/views.py", line 75, in show_traceback
    |     return render_template("airflow/traceback.html"), 500
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/flask/templating.py", line 147, in render_template
    |     return _render(app, template, context)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/flask/templating.py", line 128, in _render
    |     app.update_template_context(context)
    |   File "/home/airflow/.local/lib/python3.12/site-packages/flask/app.py", line 997, in update_template_context
    |     context.update(func())
    |                    ^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/flask_login/utils.py", line 405, in _user_context_processor
    |     return dict(current_user=_get_user())
    |                              ^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/flask_login/utils.py", line 370, in _get_user
    |     current_app.login_manager._load_user()
    |   File "/home/airflow/.local/lib/python3.12/site-packages/flask_login/login_manager.py", line 364, in _load_user
    |     user = self._user_callback(user_id)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/fab/auth_manager/security_manager/override.py", line 1396, in load_user
    |     user = self.get_user_by_id(int(pk))
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/fab/auth_manager/security_manager/override.py", line 1402, in get_user_by_id
    |     return self.session.get(self.user_model, pk)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    |     return self._get_impl(
    |            ^^^^^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    |     return db_load_fn(
    |            ^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    |     session.execute(
    |   File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1717, in execute
    |     result = conn._execute_20(statement, params or {}, execution_options)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20
    |     return meth(self, args_10style, kwargs_10style, execution_options)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    |     return connection._execute_clauseelement(
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    |     ret = self._execute_context(
    |           ^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1808, in _execute_context
    |     conn = self._revalidate_connection()
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 650, in _revalidate_connection
    |     self._invalid_transaction()
    |   File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 622, in _invalid_transaction
    |     raise exc.PendingRollbackError(
    | sqlalchemy.exc.PendingRollbackError: Can't reconnect until invalid transaction is rolled back. (Background on this error at: https://sqlalche.me/e/14/8s2b)
    +------------------------------------
INFO:     10.128.4.95:49134 - "GET /api/v2/version HTTP/1.1" 200 OK
INFO:     10.128.4.95:49142 - "GET /api/v2/version HTTP/1.1" 200 OK
INFO:     10.128.4.95:54510 - "GET /api/v2/version HTTP/1.1" 200 OK
INFO:     10.128.4.95:54504 - "GET /api/v2/version HTTP/1.1" 200 OK
INFO:     10.128.4.95:49000 - "GET /api/v2/version HTTP/1.1" 200 OK
```

**Comment by zachliu** [comment]
anyone seen the same traceback as https://github.com/apache/airflow/issues/57470#issuecomment-3472866133?
i'm using airflow 3.1.5 + fab 3.0.3 and i see both the `PendingRollbackError` and the `Error authorizing OAuth access token: mismatching_state: CSRF Warning! State not equal in request and response.`

**Comment by berglh** [comment]
I didn't see the same traceback for `/user/list` as @alex-brunshtein and seems like Okta auth provider in https://github.com/apache/airflow/issues/57470#issuecomment-3472866133 yet. Only as per my OP - but I guess the similarity is sqlalchemy that is acting as the Python object DB client and is stuck on an operation that must have timed out or failed and didn't complete rollback?

I'm wondering if it's similar to this discussion? https://github.com/sqlalchemy/sqlalchemy/discussions/8110 Maybe we're missing a commit call somewhere in the FAB provider after an execute?

**Edit**: Seems a little unlikely as there is Airflow methods for this to operate it seems which probably commit insert/update/deletes correctly.

**Comment by trina242** [comment]
> anyone seen the same traceback as [#57470 (comment)](https://github.com/apache/airflow/issues/57470#issuecomment-3472866133)? i'm using airflow 3.1.5 + fab 3.0.3 and i see both the `PendingRollbackError` and the `Error authorizing OAuth access token: mismatching_state: CSRF Warning! State not equal in request and response.`

I have the same traceback, just on Google auth, Airflow 3.1.3 and FAB 3.0.3. I didn't proceed with the upgrade yet as I'm waiting for the error to occur again to see if I can extract anything useful from `pg_stat_activity`

**Comment by alex-brunshtein** [comment]
It looks like it's a problem with FAB provider.
How to reproduce: don't logon and don't touch Security menu for 10 min. Try any Security or logon for error. 
Tested with LDAP and Keycloak auth.

**Comment by potiuk** [comment]
cc: @vincbeck :)

**Comment by zachliu** [comment]
this is by far the most comprehensive summary of the issue: https://github.com/apache/airflow/issues/57470#issuecomment-3672546381

**Comment by trina242** [comment]
After digging through FAB releases I noticed that the [fix with scoped session](https://github.com/apache/airflow/pull/58196) was not only reverted and then re-applied, but also later overridden by [this PR](https://github.com/apache/airflow/pull/58644). That would explain why the error occurs in FAB >= 3.0.3 - this fix made sense, I can see bunch of ROLLBACKs in the db with the same query_id and status `idle` so indeed it looks like the session won't close.

So the real question here is why wasn't the fix working in 3.0.2. Now I think about it I'm almost positive the stack trace was different, but it's hard to check because in my case the issue arises only after a few days.

**Comment by berglh** [comment]
@vincbeck We received the same error again after 5-7 days with the settings you suggested. Unfortunately I'm on leave and wasn't able to capture the pod logs at the time, but I assume it is the same as before.

**Comment by trina242** [comment]
No errors since downgrading FAB to version 3.0.2 (11 days ago), so I opened a PR 👆

**Comment by vincbeck** [comment]
I merged the PR, this will be released at the next provider release, that is Jan 13rd

**Comment by Komalpawar22** [comment]
Hi @trina242, I am getting the same error with FAB version `3.0.1`, it's a downgraded version only.

**Comment by patanjaliv** [comment]
database:
    sql_alchemy_pool_enabled: 'True'
    sql_alchemy_pool_size: 5
    sql_alchemy_max_overflow: 10
    sql_alchemy_pool_recycle: 600  
    sql_alchemy_pool_pre_ping: 'True'
    sql_alchemy_engine_args: '{"pool_reset_on_return": "rollback"}' 

anyone tried these values? i am monitoring my helm deployment after these changes and i need to wait and see if it fixes the issue.,

**Comment by keshan17** [comment]
> No errors since downgrading FAB to version 3.0.2 (11 days ago), so I opened a PR 👆

What's the airflow version you're using?

**Comment by trina242** [comment]
> Hi [@trina242](https://github.com/trina242), I am getting the same error with FAB version `3.0.1`, it's a downgraded version only.

I know it doesn't work in 3.0.1, only in 3.0.2. If you read the description of my PR, you'll understand why

> > No errors since downgrading FAB to version 3.0.2 (11 days ago), so I opened a PR 👆
> 
> What's the airflow version you're using?

3.1.3, but then overriding provider version to 3.0.2

**Comment by radumas** [comment]
We're on Airflow 3.1.5 with `apache-airflow-providers-fab==3.1.0`. We get similar error message but also looks like it starts with (similar to https://github.com/apache/airflow/issues/57954)

```
Jan 09 18:26:08 bash[7462]: [2026-01-09T18:26:08.918109Z] {_utils.py:59} ERROR - Exception when querying database (MessagePack data is malformed: trailing characters (byte 1)).Retrying (1/3) in 0.30s.
Jan 09 18:26:08 bash[7462]: Traceback (most recent call last):
Jan 09 18:26:08 bash[7462]:   File "/data/airflow/airflow_venv/lib/python3.10/site-packages/flask_session/_utils.py", line 52, in wrapper
Jan 09 18:26:08 bash[7462]:     return func(*args, **kwargs)
Jan 09 18:26:08 bash[7462]:   File "/data/airflow/airflow_venv/lib/python3.10/site-packages/flask_session/sqlalchemy/sqlalchemy.py", line 152, in _retrieve_session_data
Jan 09 18:26:08 bash[7462]:     return self.serializer.decode(serialized_session_data)
Jan 09 18:26:08 bash[7462]:   File "/data/airflow/airflow_venv/lib/python3.10/site-packages/airflow/providers/fab/www/session.py", line 35, in loads
Jan 09 18:26:08 bash[7462]:     return decoder.decode(data)
Jan 09 18:26:08 bash[7462]: msgspec.DecodeError: MessagePack data is malformed: trailing characters (byte 1)
``` 
which then leads into

```
Jan 09 18:26:21 bash[7459]: [2026-01-09T18:26:21.529922Z] {app.py:1744} ERROR - Exception on /login/ [POST]
#Skipping stacktrace
Jan 09 18:26:21 bash[7459]: sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) SSL connection has been closed unexpectedly
```

and then ultimately to the `sqlalchemy.exc.PendingRollbackError` error. Can post full stacktrace if helpful.

**Comment by berglh** [comment]
Hi everyone,

@jscheffl has requested we test https://pypi.org/project/apache-airflow-providers-fab/3.1.2rc1 to see if it resolves the issues which I believe @trina242 fixed in [59953](https://github.com/apache/airflow/pull/59953). I just want to get everyone to try it out because our failure mode seems to occur infrequently, it might be faster for other people in this thread to confirm continued failures.

Cheers,
Berg

**Comment by patanjaliv** [comment]
> database: sql_alchemy_pool_enabled: 'True' sql_alchemy_pool_size: 5 sql_alchemy_max_overflow: 10 sql_alchemy_pool_recycle: 600 sql_alchemy_pool_pre_ping: 'True' sql_alchemy_engine_args: '{"pool_reset_on_return": "rollback"}'
> 
> anyone tried these values? i am monitoring my helm deployment after these changes and i need to wait and see if it fixes the issue.,

This helped me to fix the issue.,

**Comment by Komalpawar22** [comment]
@here It worked for me with the fab provider version `3.0.2`

**Comment by alex-brunshtein** [comment]
> Hi everyone,
> 
> [@jscheffl](https://github.com/jscheffl) has requested we test https://pypi.org/project/apache-airflow-providers-fab/3.1.2rc1 to see if it resolves the issues which I believe [@trina242](https://github.com/trina242) fixed in [59953](https://github.com/apache/airflow/pull/59953). I just want to get everyone to try it out because our failure mode seems to occur infrequently, it might be faster for other people in this thread to confirm continued failures.
> 
> Cheers, Berg

FAB=3.1.2rc1 works good for me!  👆

**Comment by anavrotski** [comment]
FAB provider v. 3.1.2 was just released. If Airflow 3.1.6 with FAB 3.1.1 fails after some time, with 3.1.2 it fails immediately.
```
wait-for-airflow-migrations 2026-01-17T13:00:00.665096Z [info     [] Context impl MySQLImpl.        [alembic.runtime.migration] loc=migration.py:211
wait-for-airflow-migrations 2026-01-17T13:00:00.665517Z [info     [] Will assume non-transactional DDL. [alembic.runtime.migration] loc=migration.py:214
api-server   |     await self.middleware_stack(scope, receive, send)
api-server   |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
api-server   |     raise exc
api-server   |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
api-server   |     await self.app(scope, receive, _send)
api-server   |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 63, in __call__
api-server   |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
api-server   |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
api-server   |     raise exc
api-server   |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
api-server   |     await app(scope, receive, sender)
api-server   |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/routing.py", line 716, in __call__
api-server   |     await self.middleware_stack(scope, receive, send)
api-server   |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/routing.py", line 736, in app
api-server   |     await route.handle(scope, receive, send)
api-server   |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/routing.py", line 462, in handle
api-server   |     await self.app(scope, receive, send)
api-server   |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/middleware/wsgi.py", line 81, in __call__
api-server   |     await responder(receive, send)
api-server   |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/middleware/wsgi.py", line 106, in __call__
api-server   |     async with anyio.create_task_group() as task_group:
api-server   |                ^^^^^^^^^^^^^^^^^^^^^^^^^
api-server   |   File "/home/airflow/.local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 783, in __aexit__
api-server   |     raise BaseExceptionGroup(
api-server   | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
api-server   +-+---------------- 1 ----------------
api-server     | Traceback (most recent call last):
api-server     |   File "/home/airflow/.local/lib/python3.12/site-packages/flask/app.py", line 2528, in wsgi_app
api-server     |     ctx.push()
api-server     |   File "/home/airflow/.local/lib/python3.12/site-packages/flask/ctx.py", line 375, in push
api-server     |     self.session = session_interface.open_session(self.app, self.request)
api-server     |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-server     |   File "/home/airflow/.local/lib/python3.12/site-packages/flask_session/base.py", line 350, in open_session
api-server     |     saved_session_data = self._retrieve_session_data(store_id)
api-server     |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-server     |   File "/home/airflow/.local/lib/python3.12/site-packages/flask_session/_utils.py", line 56, in wrapper
api-server     |     raise e
api-server     |   File "/home/airflow/.local/lib/python3.12/site-packages/flask_session/_utils.py", line 52, in wrapper
api-server     |     return func(*args, **kwargs)
api-server     |            ^^^^^^^^^^^^^^^^^^^^^
api-server     |   File "/home/airflow/.local/lib/python3.12/site-packages/flask_session/sqlalchemy/sqlalchemy.py", line 152, in _retrieve_session_data
api-server     |     return self.serializer.decode(serialized_session_data)
api-server     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-server     |   File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/fab/www/session.py", line 35, in loads
api-server     |     return decoder.decode(data)
api-server     |            ^^^^^^^^^^^^^^^^^^^^
api-server     | msgspec.DecodeError: MessagePack data is malformed: trailing characters (byte 1)
api-server     | 
api-server     | During handling of the above exception, another exception occurred:
api-server     | 
api-server     | Traceback (most recent call last):
api-server     |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/middleware/wsgi.py", line 109, in __call__
api-server     |     await anyio.to_thread.run_sync(self.wsgi, environ, self.start_response)
api-server     |   File "/home/airflow/.local/lib/python3.12/site-packages/anyio/to_thread.py", line 63, in run_sync
api-server     |     return await get_async_backend().run_sync_in_worker_thread(
api-server     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-server     |   File "/home/airflow/.local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2502, in run_sync_in_worker_thread
api-server     |     return await future
api-server     |            ^^^^^^^^^^^^
api-server     |   File "/home/airflow/.local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 986, in run
api-server     |     result = context.run(func, *args)
api-server     |              ^^^^^^^^^^^^^^^^^^^^^^^^
api-server     |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/middleware/wsgi.py", line 147, in wsgi
api-server     |     for chunk in self.app(environ, start_response):
api-server     |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-server     |   File "/home/airflow/.local/lib/python3.12/site-packages/flask/app.py", line 2552, in __call__
api-server     |     return self.wsgi_app(environ, start_response)
api-server     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-server     |   File "/home/airflow/.local/lib/python3.12/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
api-server     |     return self.app(environ, start_response)
api-server     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-server     |   File "/home/airflow/.local/lib/python3.12/site-packages/flask/app.py", line 2532, in wsgi_app
api-server     |     response = self.handle_exception(e)
api-server     |                ^^^^^^^^^^^^^^^^^^^^^^^^
api-server     |   File "/home/airflow/.local/lib/python3.12/site-packages/flask/app.py", line 1727, in handle_exception
api-server     |     server_error = self.ensure_sync(handler)(server_error)
api-server     |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-server     |   File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/fab/www/views.py", line 75, in show_traceback
api-server     |     return render_template("airflow/traceback.html"), 500
api-server     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-server     |   File "/home/airflow/.local/lib/python3.12/site-packages/flask/templating.py", line 147, in render_template
api-server     |     return _render(app, template, context)
api-server     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-server     |   File "/home/airflow/.local/lib/python3.12/site-packages/flask/templating.py", line 128, in _render
api-server     |     app.update_template_context(context)
api-server     |   File "/home/airflow/.local/lib/python3.12/site-packages/flask/app.py", line 997, in update_template_context
api-server     |     context.update(func())
api-server     |                    ^^^^^^
api-server     |   File "/home/airflow/.local/lib/python3.12/site-packages/flask_login/utils.py", line 405, in _user_context_processor
api-server     |     return dict(current_user=_get_user())
api-server     |                              ^^^^^^^^^^^
api-server     |   File "/home/airflow/.local/lib/python3.12/site-packages/flask_login/utils.py", line 370, in _get_user
api-server     |     current_app.login_manager._load_user()
api-server     |   File "/home/airflow/.local/lib/python3.12/site-packages/flask_login/login_manager.py", line 362, in _load_user
api-server     |     user_id = session.get("_user_id")
api-server     |               ^^^^^^^^^^^
api-server     | AttributeError: 'NoneType' object has no attribute 'get'
api-server     +------------------------------------
api-server INFO:     172.25.123.143:41326 - "GET /api/v2/version HTTP/1.1" 200 OK
api-server INFO:     172.25.123.143:41334 - "GET /api/v2/version HTTP/1.1" 200 OK

```

**Comment by berglh** [comment]
@anavrotski Clearly related to FAB but what's the TaskGroup exception in the preceding traceback about? I'm still testing 3.1.2rc2 this out on 3.1.3 and it's been OK thus far.

**Comment by anavrotski** [comment]
I don't know, but I was not able to log in to the Airflow at all.

**Comment by alex-brunshtein** [comment]
Airflow 3.1.6 with FAB 3.1.2 works good in k8s.
Airflow 3.1.6. install FAB 3.1.1. by default, need to upgrade to 3.1.2

**Comment by berglh** [comment]
> I don't know, but I was not able to log in to the Airflow at all.

Are you using a custom FAB authentication provider/script or anything? Seems odd to be establishing a TaskGroup which is normally a part of a DAG not authentication related.

**Comment by anavrotski** [comment]
> > I don't know, but I was not able to log in to the Airflow at all.
> 
> Are you using a custom FAB authentication provider/script or anything? Seems odd to be establishing a TaskGroup which is normally a part of a DAG not authentication related.

We're using OAuth with Azure, configured in similar way as here - https://airflow.apache.org/docs/apache-airflow-providers-fab/stable/auth-manager/webserver-authentication.html#example-using-team-based-authorization-with-github-oauth

**Comment by berglh** [comment]
@anavrotski Sounds like it could be a bug when using custom OAuth then. Perhaps you can try it with basic authentication only first? I am about to try in the coming days something similar linking up with Amazon Cognito OIDC (Which then goes via OAuth), I will let you know if I have similar problems with 3.1.2 also.

The error you have is clearly not related to the original SQL alchemy session timeout/rollback - it seems to be related to it unpacking the response from the OAuth provider via it's session, if the issue persists and you can't find a bug in your Azure OAuth configuration, I would suggest opening a new issue.

**Comment by anavrotski** [comment]
@berglh I'm sure that basic auth will work. We have issues exactly when OAuth is used.
https://github.com/apache/airflow/issues/57485
https://github.com/apache/airflow/issues/57534
https://github.com/apache/airflow/issues/60542

**Comment by berglh** [comment]
@anavrotski Geeze, it seems you have really been struggling with that OAuth configuration 🐼 The error you posted in https://github.com/apache/airflow/issues/59349#issuecomment-3763664082 seems different from all of the three issues you referenced however. I'm assuming you tried Incognito/Private browsing mode to avoid stale cookies/browser storage etc?

**Comment by anavrotski** [comment]
My theory is that it was just a coincidence - some tasks were scheduled, and I was trying to log in at the same time. That's maybe the reason why stacktrace is mixed with task errors.
Will try to deploy Airflow 3.1.6 + FAB 3.1.2 again and post the results.

**Comment by trina242** [comment]
@anavrotski have you tried clearing cookies in the browser? I've seen this `msgspec.DecodeError: MessagePack data is malformed: trailing characters (byte 1)` on another occasion (upgrade from Airflow 2x. to 3.x) and after clearing cookies it never happened again

**Comment by jscheffl** [comment]
@wolfdn We also had some DB errors when we integrated Azure OAuth in FAB for Airflow... do you remember such error and did we need to fix anything that might be missing here?

**Comment by berglh** [comment]
I'm thinking we can call this issue closed. I don't see any reported repeats of the PendingRollBackError since 3.1.2rc2 and the 3.1.2 release. Thanks for everyone's assistance with testing and @trina242 and @vincbeck for resolving this one.

**Comment by anavrotski** [comment]
@trina242 thanks, your advice helped.
P.S. Without clearing cookies, the issue was reproduced, still with a TaskGroup exception in the stacktrace.

**Comment by zachliu** [comment]
@anavrotski we're using OAuth with Auth0, also configured in similar way as you mentioned - https://airflow.apache.org/docs/apache-airflow-providers-fab/stable/auth-manager/webserver-authentication.html#example-using-team-based-authorization-with-github-oauth
we are too seeing the `TaskGroup` exception as well as the `PendingRollbackError` exception in airflow 3.1.6 + fab 3.1.1

**Comment by wolvery** [comment]
We have seen it happening in 3.1.6, to overcome the issue for some time, we are restarting the pods.

**Comment by AndersFarrFoundry** [comment]
Happening for me as well in 3.1.6 - helm + kubernetes install.

**Comment by Dmitrij-Salenkoff** [comment]
Still happening to me as well. airflow 3.1.6 + fab 3.1.2 - helm and k8s

**Comment by berglh** [comment]
@zachliu You need to upgrade fab provider to 3.1.2 and clear your cookies in your browser.

@wolvery & @AndersFarrFoundry Can you confirm you both upgraded fab provider manually to 3.1.2? You'll need to do this either with start-up script or custom Airflow container in your helm installation or use a newer version of Airflow with the new provider baked in already.

@Dmitrij-Salenkoff Can you please try these settings below as well with FAB 3.1.2? Are you using OAuth/SAML provider? Seems there are issues with OAuth/SAML providers which I think is a separate bug.

> Can someone please try these fixes:
> 
> ```
> [database]
> sql_alchemy_pool_pre_ping = True
> 
> [fab]
> session_lifetime_minutes = 1440
> ```
> 
> I would like to see if these config changes fix the issue. If yes, I'll create a PR to change the default value of these configs

**Comment by uplsh580** [comment]
Resolved in airflow 3.1.7 + apache-airflow-providers-fab==3.2.0
Everyone, please upgrade your version.

**Comment by rgelsi** [comment]
I’m still getting this error with Airflow 3.1.7 + fab 3.2.0 (K8s Helm installation)

**Comment by fbmatilla** [comment]
Same problem here, also Airflow 3.1.7 + FAB Provider 3.2.0 (Helm Installation).

**Comment by uplsh580** [comment]
> Resolved in airflow 3.1.7 + apache-airflow-providers-fab==3.2.0
> Everyone, please upgrade your version.

Sorry about that. I thought the issue with the Airflow Security tab was fully resolved, but it’s actually still happening in some case.

**Comment by vincbeck** [comment]
https://github.com/apache/airflow/pull/61480 seems to have a fix for it. Can you guys check and test it (if possible)?

**Comment by anavrotski** [comment]
I've created a new issue as soon as this is closed
https://github.com/apache/airflow/issues/61518
